from django.contrib import admin

from .models import IntegrationMutationApproval, IntegrationRequestLog, IntegrationToken


@admin.register(IntegrationToken)
class IntegrationTokenAdmin(admin.ModelAdmin):
    list_display = ('name', 'prefix', 'is_active', 'scope_summary', 'expires_at', 'last_used_at', 'created_at')
    list_filter = ('is_active',)
    search_fields = ('name', 'prefix', 'notes')
    readonly_fields = ('prefix', 'secret_digest', 'last_used_at', 'created_at', 'updated_at')
    fields = ('name', 'prefix', 'scopes', 'is_active', 'expires_at', 'last_used_at', 'created_by', 'notes', 'created_at', 'updated_at', 'secret_digest')

    @admin.display(description='Scopes')
    def scope_summary(self, obj):
        return ', '.join(obj.scopes or [])

    def has_add_permission(self, request):
        # Tokens must be generated by the one-time-secret management command.
        return False


@admin.register(IntegrationMutationApproval)
class IntegrationMutationApprovalAdmin(admin.ModelAdmin):
    list_display = ('created_at', 'token', 'operation', 'expires_at', 'consumed_at', 'nonce')
    list_filter = ('operation',)
    search_fields = ('nonce', 'token__name', 'token__prefix')
    readonly_fields = ('token', 'nonce', 'operation', 'payload_digest', 'expires_at', 'consumed_at', 'created_at')

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


@admin.register(IntegrationRequestLog)
class IntegrationRequestLogAdmin(admin.ModelAdmin):
    list_display = ('created_at', 'token', 'method', 'path', 'scope', 'status_code', 'request_id')
    list_filter = ('method', 'scope', 'status_code')
    search_fields = ('request_id', 'path', 'token__name', 'token__prefix')
    readonly_fields = ('token', 'request_id', 'method', 'path', 'scope', 'status_code', 'remote_addr', 'created_at')

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False
