# Generated by Django 5.2.15 on 2026-06-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_display_on_pos_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("poster", "ملصق الفعالية"),
                            ("cover", "صورة الغلاف"),
                            ("gallery", "معرض الصور"),
                        ],
                        default="gallery",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="صورة أساسية"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="events.event",
                    ),
                ),
                (
                    "media_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_media",
                        to="catalog.mediaasset",
                        verbose_name="صورة الفعالية",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة الفعالية",
                "verbose_name_plural": "صور الفعاليات",
                "ordering": ["role", "sort_order", "-is_primary", "created_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "event",
                            "role",
                            "is_active",
                            "is_primary",
                            "sort_order",
                        ],
                        name="events_even_event_i_bd13ab_idx",
                    )
                ],
            },
        ),
    ]
