from decimal import Decimal, InvalidOperation

from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render

from accounts.permissions import require_staff_capability
from core.models import InventoryItem, Product, ProductRecipeItem
from core.stock_recipes import calculate_recipe_cost, update_product_cost_from_recipe


inventory_required = require_staff_capability('inventory')


def _decimal(value, label, minimum=None):
    try:
        number = Decimal(str(value).strip())
    except (InvalidOperation, TypeError, ValueError):
        raise ValidationError(f'{label}: أدخل رقماً صالحاً.')
    if minimum is not None and number < minimum:
        raise ValidationError(f'{label}: يجب ألا تقل القيمة عن {minimum}.')
    return number


def _product_rows(query=''):
    products = (
        Product.objects.select_related('category')
        .annotate(
            active_recipe_count=Count(
                'recipe_items',
                filter=Q(recipe_items__is_active=True),
                distinct=True,
            )
        )
        .order_by('category__name_ar', 'name_ar', 'id')
    )
    if query:
        products = products.filter(
            Q(name_ar__icontains=query)
            | Q(name_en__icontains=query)
            | Q(category__name_ar__icontains=query)
            | Q(category__name_en__icontains=query)
        )

    rows = []
    for product in products[:400]:
        recipe = calculate_recipe_cost(product)
        rows.append({'product': product, 'recipe': recipe})
    return rows


@inventory_required
def staff_recipe_manager(request):
    query = (request.GET.get('q') or '').strip()
    return render(
        request,
        'staff/recipe_manager.html',
        {
            'rows': _product_rows(query),
            'query': query,
        },
    )


def _posted_rows(request):
    line_ids = request.POST.getlist('line_id')
    inventory_items = request.POST.getlist('inventory_item')
    quantities = request.POST.getlist('quantity_per_unit')
    units = request.POST.getlist('unit')
    wastes = request.POST.getlist('waste_factor_percent')
    active_values = request.POST.getlist('is_active')
    notes = request.POST.getlist('notes')
    actions = request.POST.getlist('action')

    lengths = {
        len(line_ids),
        len(inventory_items),
        len(quantities),
        len(units),
        len(wastes),
        len(active_values),
        len(notes),
        len(actions),
    }
    if len(lengths) != 1:
        raise ValidationError('تعذر قراءة صفوف الوصفة. أعد تحميل الصفحة وحاول مجدداً.')

    rows = []
    for values in zip(
        line_ids,
        inventory_items,
        quantities,
        units,
        wastes,
        active_values,
        notes,
        actions,
    ):
        line_id, inventory_item, quantity, unit, waste, is_active, note, action = values
        rows.append(
            {
                'line_id': line_id.strip(),
                'inventory_item': inventory_item.strip(),
                'quantity_per_unit': quantity.strip(),
                'unit': unit.strip(),
                'waste_factor_percent': waste.strip() or '0',
                'is_active': is_active == '1',
                'notes': note.strip(),
                'action': action.strip() or 'keep',
            }
        )
    return rows


def _validate_rows(product, rows):
    unit_values = {value for value, _label in InventoryItem.Unit.choices}
    existing = {
        str(line.pk): line
        for line in product.recipe_items.select_related('inventory_item').all()
    }
    cleaned = []
    seen = set()

    for index, row in enumerate(rows, start=1):
        line_id = row['line_id']
        action = row['action']
        if line_id and line_id not in existing:
            raise ValidationError(f'الصف {index}: هذا المكوّن لا يتبع هذا المنتج.')
        if action == 'delete':
            if line_id:
                cleaned.append({'action': 'delete', 'line': existing[line_id]})
            continue

        if not row['inventory_item']:
            # Leave the empty row generated by the UI unused.
            if not line_id and not row['quantity_per_unit'] and not row['unit']:
                continue
            raise ValidationError(f'الصف {index}: اختر مادة مخزون.')
        try:
            inventory_item = InventoryItem.objects.get(pk=int(row['inventory_item']))
        except (InventoryItem.DoesNotExist, TypeError, ValueError):
            raise ValidationError(f'الصف {index}: مادة المخزون غير صالحة.')

        if row['unit'] not in unit_values:
            raise ValidationError(f'الصف {index}: وحدة القياس غير صالحة.')
        quantity = _decimal(row['quantity_per_unit'], f'الصف {index} / الكمية', Decimal('0.001'))
        waste = _decimal(row['waste_factor_percent'], f'الصف {index} / الهدر', Decimal('0'))

        duplicate_key = (inventory_item.pk, row['unit'])
        if duplicate_key in seen:
            raise ValidationError(
                f'الصف {index}: لا يمكن تكرار نفس مادة المخزون بنفس وحدة القياس.'
            )
        seen.add(duplicate_key)
        cleaned.append(
            {
                'action': 'save',
                'line': existing.get(line_id),
                'inventory_item': inventory_item,
                'quantity_per_unit': quantity,
                'unit': row['unit'],
                'waste_factor_percent': waste,
                'is_active': row['is_active'],
                'notes': row['notes'],
            }
        )
    return cleaned


@inventory_required
def staff_recipe_edit(request, product_id):
    product = get_object_or_404(Product.objects.select_related('category'), pk=product_id)
    posted_rows = None

    if request.method == 'POST':
        try:
            posted_rows = _posted_rows(request)
            with transaction.atomic():
                product = Product.objects.select_for_update().get(pk=product.pk)
                cleaned = _validate_rows(product, posted_rows)
                for row in cleaned:
                    if row['action'] == 'delete':
                        row['line'].delete()
                        continue
                    line = row['line'] or ProductRecipeItem(product=product)
                    line.inventory_item = row['inventory_item']
                    line.quantity_per_unit = row['quantity_per_unit']
                    line.unit = row['unit']
                    line.waste_factor_percent = row['waste_factor_percent']
                    line.is_active = row['is_active']
                    line.notes = row['notes']
                    line.full_clean()
                    line.save()
                recipe = update_product_cost_from_recipe(product, request.user)
            messages.success(
                request,
                f"تم حفظ الوصفة وتحديث كلفة المنتج إلى {recipe['recipe_estimated_unit_cost_syp']:.0f}.",
            )
            return redirect('staff_recipe_edit', product_id=product.pk)
        except (ValidationError, IntegrityError) as exc:
            if isinstance(exc, ValidationError):
                error_messages = exc.messages
            else:
                error_messages = ['يوجد مكوّن مكرر أو تعارض في بيانات الوصفة.']
            for message in error_messages:
                messages.error(request, message)

    recipe = calculate_recipe_cost(product)
    lines = list(product.recipe_items.select_related('inventory_item').order_by('id'))
    current_item_ids = {line.inventory_item_id for line in lines}
    inventory_items = InventoryItem.objects.filter(
        Q(is_active=True) | Q(pk__in=current_item_ids)
    ).order_by('name_ar', 'name_en', 'id')

    return render(
        request,
        'staff/recipe_edit.html',
        {
            'product': product,
            'recipe': recipe,
            'lines': lines,
            'inventory_items': inventory_items,
            'units': InventoryItem.Unit.choices,
            'posted_rows': posted_rows,
        },
    )
