# Generated by Django 5.2.14 on 2026-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_total_syp_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_options_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
