# Generated by Django 5.2.14 on 2026-05-30 08:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_orderitem_item_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("title_ar", models.CharField(max_length=160)),
                ("title_en", models.CharField(blank=True, max_length=160)),
                ("subtitle_ar", models.CharField(blank=True, max_length=240)),
                ("subtitle_en", models.CharField(blank=True, max_length=240)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "تسمية صفحة",
                "verbose_name_plural": "تسميات الصفحات",
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_title_ar",
                    models.CharField(default="نظام مشاريب", max_length=160),
                ),
                (
                    "system_title_en",
                    models.CharField(default="Masharib System", max_length=160),
                ),
                (
                    "public_brand_title_ar",
                    models.CharField(default="مشاريب", max_length=160),
                ),
                (
                    "public_brand_title_en",
                    models.CharField(default="Masharib", max_length=160),
                ),
                (
                    "header_subtitle_ar",
                    models.CharField(
                        default="Hub Sueda • تشغيل يومي مرن", max_length=220
                    ),
                ),
                (
                    "header_subtitle_en",
                    models.CharField(
                        default="Hub Sueda • flexible daily operations", max_length=220
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("ar", "العربية"), ("en", "English")],
                        default="ar",
                        max_length=5,
                    ),
                ),
                ("enable_takeaway", models.BooleanField(default=False)),
                ("enable_table_orders", models.BooleanField(default=True)),
                ("enable_general_in_space_orders", models.BooleanField(default=True)),
                ("show_internal_order_uuid", models.BooleanField(default=False)),
                (
                    "default_order_mode",
                    models.CharField(
                        choices=[
                            ("dine_in", "طلب عام داخل المكان"),
                            ("table", "طلب طاولة"),
                            ("takeaway", "تيك أواي"),
                        ],
                        default="dine_in",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#0f5f57", max_length=20)),
                ("header_color", models.CharField(default="#0f5f57", max_length=20)),
                ("button_color", models.CharField(default="#0f5f57", max_length=20)),
                ("accent_color", models.CharField(default="#c88a2b", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#f6f1e8", max_length=20),
                ),
                (
                    "card_background_color",
                    models.CharField(default="#fffaf1", max_length=20),
                ),
                ("text_color", models.CharField(default="#262626", max_length=20)),
                ("border_color", models.CharField(default="#ddd2c0", max_length=20)),
                ("base_font_size_px", models.PositiveIntegerField(default=18)),
                (
                    "heading_font_size_px",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("border_radius_px", models.PositiveIntegerField(default=18)),
                ("custom_font_name", models.CharField(blank=True, max_length=120)),
                (
                    "custom_font_file",
                    models.FileField(
                        blank=True,
                        upload_to="system/fonts/",
                        validators=[core.models.validate_font_upload],
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="service_mode",
            field=models.CharField(
                choices=[
                    ("dine_in", "طلب عام داخل المكان"),
                    ("table", "طلب طاولة"),
                    ("takeaway", "تيك أواي"),
                ],
                default="dine_in",
                max_length=20,
            ),
        ),
    ]
