# Generated by Django 5.2.14 on 2026-05-31 19:42

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pagesetting_systemsetting_order_service_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="button_font_size_px",
            field=models.PositiveIntegerField(
                default=16,
                validators=[
                    django.core.validators.MinValueValidator(13),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="حجم خط الأزرار",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="button_padding_scale",
            field=models.CharField(
                choices=[("compact", "مضغوط"), ("normal", "عادي"), ("large", "كبير")],
                default="normal",
                max_length=20,
                verbose_name="حجم حشوة الأزرار",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="card_shadow_level",
            field=models.CharField(
                choices=[
                    ("none", "بدون ظل"),
                    ("soft", "ظل خفيف"),
                    ("medium", "ظل متوسط"),
                ],
                default="soft",
                max_length=20,
                verbose_name="ظل البطاقات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="cart_review_position",
            field=models.CharField(
                choices=[
                    ("bottom", "أسفل الصفحة"),
                    ("sidebar_desktop", "شريط جانبي على سطح المكتب"),
                    ("modal_drawer", "درج/نافذة للمراجعة"),
                ],
                default="bottom",
                max_length=30,
                verbose_name="مكان مراجعة السلة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="cashier_layout",
            field=models.CharField(
                choices=[
                    ("single_column", "عمود واحد"),
                    ("summary_sidebar", "ملخص جانبي"),
                    ("large_payment", "دفع كبير"),
                ],
                default="single_column",
                max_length=30,
                verbose_name="تخطيط الكاشير",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="collapse_modifiers_by_default",
            field=models.BooleanField(
                default=True, verbose_name="طي خيارات المنتجات افتراضياً"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="input_size",
            field=models.CharField(
                choices=[("compact", "مضغوط"), ("normal", "عادي"), ("large", "كبير")],
                default="normal",
                max_length=20,
                verbose_name="حجم حقول الإدخال",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="menu_desktop_columns",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                default=3,
                verbose_name="أعمدة المنيو على سطح المكتب",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="menu_layout_preset",
            field=models.CharField(
                choices=[
                    ("default_masharib", "مشاريب الافتراضي"),
                    ("minimal_fast", "سريع وبسيط"),
                    ("visual_cards", "بطاقات بصرية"),
                    ("compact_list", "قائمة مضغوطة"),
                    ("tablet_grid", "شبكة تابلت"),
                ],
                default="default_masharib",
                max_length=30,
                verbose_name="نمط تخطيط المنيو",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="menu_mobile_layout",
            field=models.CharField(
                choices=[
                    ("list", "قائمة"),
                    ("one_column_cards", "بطاقات عمود واحد"),
                    ("large_image_cards", "بطاقات صور كبيرة"),
                ],
                default="one_column_cards",
                max_length=30,
                verbose_name="تخطيط الجوال للمنيو",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="menu_tablet_columns",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")],
                default=2,
                verbose_name="أعمدة المنيو على التابلت",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="muted_text_color",
            field=models.CharField(
                default="#6b6b6b",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون النص الثانوي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="order_board_density",
            field=models.CharField(
                choices=[
                    ("compact", "مضغوط"),
                    ("normal", "عادي"),
                    ("large_touch", "لمس كبير"),
                ],
                default="normal",
                max_length=20,
                verbose_name="كثافة لوحة الطلبات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="page_max_width_px",
            field=models.PositiveIntegerField(
                default=1200,
                validators=[
                    django.core.validators.MinValueValidator(360),
                    django.core.validators.MaxValueValidator(1600),
                ],
                verbose_name="أقصى عرض للصفحة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_cart_position",
            field=models.CharField(
                choices=[("bottom", "أسفل"), ("side", "جانب"), ("drawer", "درج")],
                default="side",
                max_length=20,
                verbose_name="مكان سلة POS",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_desktop_columns",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")],
                default=4,
                verbose_name="أعمدة POS على سطح المكتب",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_enable_search_bar",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل شريط البحث في POS"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_layout_preset",
            field=models.CharField(
                choices=[
                    ("fast_touch", "لمس سريع"),
                    ("image_grid", "شبكة صور"),
                    ("compact_list", "قائمة مضغوطة"),
                    ("tablet_split", "تقسيم تابلت"),
                ],
                default="fast_touch",
                max_length=30,
                verbose_name="نمط نقطة البيع",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_mobile_columns",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2")],
                default=2,
                verbose_name="أعمدة POS على الجوال",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_show_prices",
            field=models.BooleanField(
                default=True, verbose_name="إظهار الأسعار في POS"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_show_product_images",
            field=models.BooleanField(
                default=True, verbose_name="إظهار صور المنتجات في POS"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_show_section_chips",
            field=models.BooleanField(
                default=True, verbose_name="إظهار شرائح الأقسام في POS"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_tablet_columns",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")],
                default=3,
                verbose_name="أعمدة POS على التابلت",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="product_card_style",
            field=models.CharField(
                choices=[
                    ("minimal", "بسيط"),
                    ("image_first", "الصورة أولاً"),
                    ("text_first", "النص أولاً"),
                    ("compact", "مضغوط"),
                    ("story_card", "بطاقة قصة"),
                ],
                default="image_first",
                max_length=30,
                verbose_name="شكل بطاقة المنتج",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_brand_name",
            field=models.BooleanField(default=True, verbose_name="إظهار اسم العلامة"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_customer_name_field",
            field=models.BooleanField(
                default=True, verbose_name="إظهار حقل اسم الزبون"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_customer_phone_field",
            field=models.BooleanField(
                default=True, verbose_name="إظهار حقل هاتف الزبون"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_general_note_field",
            field=models.BooleanField(
                default=True, verbose_name="إظهار حقل الملاحظة العامة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_header_subtitle",
            field=models.BooleanField(default=True, verbose_name="إظهار وصف الهيدر"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_item_notes",
            field=models.BooleanField(
                default=True, verbose_name="إظهار ملاحظات العناصر"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_modifier_summary",
            field=models.BooleanField(default=True, verbose_name="إظهار ملخص الخيارات"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_product_badges",
            field=models.BooleanField(
                default=True, verbose_name="إظهار شارات المنتجات"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_product_descriptions",
            field=models.BooleanField(default=True, verbose_name="إظهار وصف المنتجات"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_product_images",
            field=models.BooleanField(default=True, verbose_name="إظهار صور المنتجات"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_product_prices",
            field=models.BooleanField(default=True, verbose_name="إظهار الأسعار"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_public_header",
            field=models.BooleanField(
                default=True, verbose_name="إظهار هيدر المنيو العام"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_section_chips",
            field=models.BooleanField(default=True, verbose_name="إظهار شرائح الأقسام"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_sticky_cart",
            field=models.BooleanField(default=True, verbose_name="إظهار السلة اللاصقة"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_table_banner",
            field=models.BooleanField(
                default=True, verbose_name="إظهار شريط الطاولة/المكان"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="small_font_size_px",
            field=models.PositiveIntegerField(
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(11),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="حجم الخط الصغير",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="staff_home_layout",
            field=models.CharField(
                choices=[
                    ("grouped_cards", "بطاقات مجمّعة"),
                    ("compact_grid", "شبكة مضغوطة"),
                    ("large_touch", "لمس كبير"),
                ],
                default="grouped_cards",
                max_length=30,
                verbose_name="تخطيط صفحة الفريق",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="sticky_cart_style",
            field=models.CharField(
                choices=[
                    ("bottom_bar", "شريط سفلي"),
                    ("floating_button", "زر عائم"),
                    ("sidebar_on_desktop", "جانبياً على سطح المكتب"),
                ],
                default="bottom_bar",
                max_length=30,
                verbose_name="شكل السلة اللاصقة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="ui_density",
            field=models.CharField(
                choices=[
                    ("compact", "مضغوط"),
                    ("comfortable", "مريح"),
                    ("large_touch", "لمس كبير"),
                ],
                default="comfortable",
                max_length=20,
                verbose_name="كثافة الواجهة",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="accent_color",
            field=models.CharField(
                default="#c88a2b",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون التمييز",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="background_color",
            field=models.CharField(
                default="#f6f1e8",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون خلفية الصفحة",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="base_font_size_px",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(13),
                    django.core.validators.MaxValueValidator(22),
                ],
                verbose_name="حجم الخط الأساسي",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="border_color",
            field=models.CharField(
                default="#ddd2c0",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون الحدود",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="border_radius_px",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32),
                ],
                verbose_name="استدارة الزوايا",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="button_color",
            field=models.CharField(
                default="#0f5f57",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون الأزرار",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="card_background_color",
            field=models.CharField(
                default="#fffaf1",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون خلفية البطاقات",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="custom_font_file",
            field=models.FileField(
                blank=True,
                upload_to="system/fonts/",
                validators=[core.models.validate_font_upload],
                verbose_name="ملف الخط المخصص",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="custom_font_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="اسم الخط المخصص"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="default_language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "English")],
                default="ar",
                max_length=5,
                verbose_name="اللغة الافتراضية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="default_order_mode",
            field=models.CharField(
                choices=[
                    ("dine_in", "طلب عام داخل المكان"),
                    ("table", "طلب طاولة"),
                    ("takeaway", "تيك أواي"),
                ],
                default="dine_in",
                max_length=20,
                verbose_name="وضع الطلب الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="enable_general_in_space_orders",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل الطلب العام داخل المكان"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="enable_table_orders",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل طلبات الطاولات"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="enable_takeaway",
            field=models.BooleanField(default=False, verbose_name="تفعيل التيك أواي"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="header_color",
            field=models.CharField(
                default="#0f5f57",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون الهيدر",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="header_subtitle_ar",
            field=models.CharField(
                default="Hub Sueda • تشغيل يومي مرن",
                max_length=220,
                verbose_name="وصف الهيدر بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="header_subtitle_en",
            field=models.CharField(
                default="Hub Sueda • flexible daily operations",
                max_length=220,
                verbose_name="وصف الهيدر بالإنجليزية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="heading_font_size_px",
            field=models.PositiveIntegerField(
                default=34,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(44),
                ],
                verbose_name="حجم العناوين",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="primary_color",
            field=models.CharField(
                default="#0f5f57",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="اللون الأساسي",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="public_brand_title_ar",
            field=models.CharField(
                default="مشاريب", max_length=160, verbose_name="اسم العلامة في المنيو"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="public_brand_title_en",
            field=models.CharField(
                default="Masharib",
                max_length=160,
                verbose_name="اسم العلامة بالإنجليزية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="show_internal_order_uuid",
            field=models.BooleanField(
                default=False, verbose_name="إظهار رقم UUID الداخلي"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="system_title_ar",
            field=models.CharField(
                default="نظام مشاريب",
                max_length=160,
                verbose_name="عنوان النظام بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="system_title_en",
            field=models.CharField(
                default="Masharib System",
                max_length=160,
                verbose_name="عنوان النظام بالإنجليزية",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="text_color",
            field=models.CharField(
                default="#262626",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون النص",
            ),
        ),
    ]
