# Generated by Django 5.2.14 on 2026-05-31 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_internet_session_fields(apps, schema_editor):
    InternetSession = apps.get_model("core", "InternetSession")
    for session in InternetSession.objects.all().iterator():
        updates = []
        if session.start_time and not session.started_at:
            session.started_at = session.start_time
            updates.append("started_at")
        if session.end_time and not session.ended_at and session.status != "active":
            session.ended_at = session.end_time
            updates.append("ended_at")
        if session.actual_duration_minutes is not None and session.duration_minutes is None:
            session.duration_minutes = session.actual_duration_minutes
            updates.append("duration_minutes")
        if session.customer_name and not session.guest_name:
            session.guest_name = session.customer_name
            updates.append("guest_name")
        if session.customer_phone and not session.guest_phone:
            session.guest_phone = session.customer_phone
            updates.append("guest_phone")
        if updates:
            session.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemsetting_button_font_size_px_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internetsession",
            name="access_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="bandwidth_profile",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("prepaid", "مسبق الدفع"),
                    ("open_metered", "مفتوح محسوب بالوقت"),
                    ("free", "مجاني"),
                    ("manual", "يدوي"),
                ],
                default="open_metered",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="calculated_total_syp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="daily_cap_syp",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="device_mac",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ended_internet_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="free_grace_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="guest_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="ip_address",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="linked_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internet_sessions",
                to="core.order",
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="linked_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internet_sessions",
                to="core.payment",
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="manual_total_syp",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="minimum_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="network_provider",
            field=models.CharField(
                choices=[
                    ("manual", "يدوي"),
                    ("mikrotik", "MikroTik"),
                    ("unifi", "UniFi"),
                    ("radius", "RADIUS"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="network_session_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="network_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="rate_per_hour_syp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_internet_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="allow_guest_internet_sessions",
            field=models.BooleanField(
                default=True, verbose_name="السماح بجلسات الزوار"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="allow_member_internet_sessions",
            field=models.BooleanField(
                default=True, verbose_name="السماح بجلسات الأعضاء"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="auto_create_order_for_metered_sessions",
            field=models.BooleanField(
                default=False, verbose_name="إنشاء طلب تلقائي للجلسات المحسوبة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_daily_cap_syp",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="السقف اليومي الافتراضي"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_free_grace_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="دقائق السماح المجانية الافتراضية"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_internet_billing_mode",
            field=models.CharField(
                choices=[
                    ("prepaid", "مسبق الدفع"),
                    ("open_metered", "مفتوح محسوب بالوقت"),
                    ("free", "مجاني"),
                    ("manual", "يدوي"),
                ],
                default="open_metered",
                max_length=20,
                verbose_name="وضع فوترة الإنترنت الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_minimum_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="الحد الأدنى الافتراضي للدقائق"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_rate_per_hour_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="سعر الساعة الافتراضي للإنترنت/العمل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="internet_service_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internet_setting_profiles",
                to="core.product",
                verbose_name="منتج خدمة الإنترنت للطلبات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="require_phone_for_guest_session",
            field=models.BooleanField(
                default=False, verbose_name="طلب هاتف الزائر عند بدء الجلسة"
            ),
        ),
        migrations.RunPython(copy_legacy_internet_session_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="internetsession",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internetsession",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="core.internetpackage",
            ),
        ),
        migrations.AlterField(
            model_name="internetsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعالة"),
                    ("ended", "منتهية"),
                    ("cancelled", "ملغاة"),
                    ("unpaid", "غير مدفوعة"),
                    ("paid", "مدفوعة"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
