# Generated by Django 5.2.14 on 2026-05-31 20:09

from django.db import migrations, models


def backfill_order_fulfillment(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    Order.objects.filter(table__isnull=False).update(fulfillment_mode='table')
    Order.objects.filter(table__isnull=True, service_mode='takeaway').update(fulfillment_mode='takeaway')
    Order.objects.filter(delivery_fee_syp__lt=0).update(delivery_fee_syp=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemsetting_button_font_size_px_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_driver_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="اسم السائق"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="assigned_driver_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="هاتف السائق"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, verbose_name="عنوان التوصيل"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_area",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="منطقة التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_eta_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="زمن التوصيل المتوقع بالدقائق"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee_syp",
            field=models.PositiveIntegerField(default=0, verbose_name="رسوم التوصيل"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات التوصيل"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("not_delivery", "ليس توصيل"),
                    ("delivery_requested", "طلب توصيل"),
                    ("confirmed", "مؤكد"),
                    ("preparing", "قيد التحضير"),
                    ("ready_for_dispatch", "جاهز للإرسال"),
                    ("out_for_delivery", "خرج للتوصيل"),
                    ("delivered", "تم التسليم"),
                    ("failed", "فشل التوصيل"),
                    ("cancelled", "ملغى"),
                ],
                default="not_delivery",
                max_length=30,
                verbose_name="حالة التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("inside_space", "طلب داخل المكان"),
                    ("table", "طاولة"),
                    ("delivery", "توصيل"),
                    ("takeaway", "تيك أواي"),
                ],
                default="inside_space",
                max_length=20,
                verbose_name="وضع الاستلام/التنفيذ",
            ),
        ),
        migrations.RunPython(backfill_order_fulfillment, noop_reverse),
        migrations.AddField(
            model_name="systemsetting",
            name="default_fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("inside_space", "طلب داخل المكان"),
                    ("table", "طاولة"),
                    ("delivery", "توصيل"),
                    ("takeaway", "تيك أواي"),
                ],
                default="inside_space",
                max_length=20,
                verbose_name="وضع التنفيذ الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_contact_phone",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="هاتف التواصل للتوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_contact_whatsapp",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="واتساب التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_fee_mode",
            field=models.CharField(
                choices=[
                    ("none", "بدون رسوم"),
                    ("fixed", "رسوم ثابتة"),
                    ("manual", "إدخال يدوي"),
                ],
                default="none",
                max_length=20,
                verbose_name="طريقة رسوم التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات التوصيل"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_working_hours_text",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="ساعات عمل التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="enable_delivery",
            field=models.BooleanField(
                default=False,
                help_text="يبقى خيار التوصيل مخفياً في المنيو وPOS ما لم يتم تفعيله.",
                verbose_name="تفعيل التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="fixed_delivery_fee_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="رسوم التوصيل الثابتة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="minimum_delivery_order_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الحد الأدنى لطلب التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="require_address_for_delivery",
            field=models.BooleanField(default=True, verbose_name="طلب العنوان للتوصيل"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="require_phone_for_delivery",
            field=models.BooleanField(default=True, verbose_name="طلب الهاتف للتوصيل"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="enable_takeaway",
            field=models.BooleanField(
                default=False,
                help_text="يبقى خيار التيك أواي مخفياً في المنيو وPOS ما لم يتم تفعيله.",
                verbose_name="تفعيل التيك أواي",
            ),
        ),
    ]
