# Generated by Django 5.2.15 on 2026-06-19 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_orderitem_prep_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الإلغاء"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_changed_mind", "غيّر الزبون رأيه"),
                    ("item_unavailable", "المنتج غير متوفر"),
                    ("staff_mistake", "خطأ من الموظف"),
                    ("duplicate_order", "طلب مكرر"),
                    ("quality_issue", "مشكلة جودة"),
                    ("manager_decision", "قرار المدير"),
                    ("other", "سبب آخر"),
                ],
                max_length=30,
                verbose_name="سبب الإلغاء",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت الإلغاء"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ألغاه",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cancellation_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الإلغاء"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_changed_mind", "غيّر الزبون رأيه"),
                    ("item_unavailable", "المنتج غير متوفر"),
                    ("staff_mistake", "خطأ من الموظف"),
                    ("duplicate_order", "طلب مكرر"),
                    ("quality_issue", "مشكلة جودة"),
                    ("manager_decision", "قرار المدير"),
                    ("other", "سبب آخر"),
                ],
                max_length=30,
                verbose_name="سبب الإلغاء",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الدفع"),
        ),
        migrations.AddField(
            model_name="payment",
            name="reversal_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer_changed_mind", "غيّر الزبون رأيه"),
                    ("item_unavailable", "المنتج غير متوفر"),
                    ("staff_mistake", "خطأ من الموظف"),
                    ("duplicate_order", "طلب مكرر"),
                    ("quality_issue", "مشكلة جودة"),
                    ("manager_decision", "قرار المدير"),
                    ("other", "سبب آخر"),
                ],
                max_length=30,
                verbose_name="سبب عكس الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "مبلغ ثابت"),
                            ("percentage", "نسبة مئوية"),
                            ("comp", "ضيافة"),
                            ("correction", "تصحيح"),
                            ("member", "عضو"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="نوع الخصم",
                    ),
                ),
                ("amount_syp", models.PositiveIntegerField(verbose_name="الخصم")),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="النسبة",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="سبب الخصم")),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_order_discounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="موافقة المدير",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_order_discounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discounts",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_date",
                    models.DateField(unique=True, verbose_name="تاريخ العمل"),
                ),
                (
                    "opening_cash_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="النقد الافتتاحي"
                    ),
                ),
                (
                    "cash_sales_syp",
                    models.PositiveIntegerField(default=0, verbose_name="مبيعات نقدية"),
                ),
                (
                    "non_cash_sales_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبيعات غير نقدية"
                    ),
                ),
                (
                    "total_payments_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الدفعات"
                    ),
                ),
                (
                    "unpaid_orders_syp",
                    models.PositiveIntegerField(default=0, verbose_name="غير مدفوع"),
                ),
                (
                    "partial_payments_syp",
                    models.PositiveIntegerField(default=0, verbose_name="مدفوع جزئياً"),
                ),
                (
                    "discounts_syp",
                    models.PositiveIntegerField(default=0, verbose_name="الخصومات"),
                ),
                (
                    "cancelled_orders_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="قيمة الطلبات الملغاة"
                    ),
                ),
                (
                    "refunds_or_reversals_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="المسترد/المعكوس"
                    ),
                ),
                (
                    "expected_cash_syp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="النقد المتوقع"
                    ),
                ),
                (
                    "actual_cash_counted_syp",
                    models.PositiveIntegerField(default=0, verbose_name="النقد الفعلي"),
                ),
                (
                    "cash_difference_syp",
                    models.IntegerField(default=0, verbose_name="الفرق"),
                ),
                ("notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("is_finalized", models.BooleanField(default=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_finalized", True)),
                        fields=("business_date",),
                        name="unique_finalized_daily_close_per_date",
                    )
                ],
            },
        ),
    ]
