# Generated by Django 5.2.15 on 2026-06-19 20:25

import django.db.models.deletion
from django.db import migrations, models




def classify_products_and_items(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    OrderItem = apps.get_model("core", "OrderItem")
    PrepStation = apps.get_model("catalog", "PrepStation")
    stations = {s.code: s for s in PrepStation.objects.filter(code__in=["kitchen", "bar", "cashier", "service", "general"])}
    for product in Product.objects.all().iterator():
        item_type = product.item_type
        service_type = product.service_type
        if item_type == "food":
            product.product_type = "food"
            product.requires_preparation = True
            product.prep_station_ref_id = product.prep_station_ref_id or getattr(stations.get("kitchen"), "id", None)
        elif item_type == "beverage":
            product.product_type = "drink"
            product.requires_preparation = True
            product.prep_station_ref_id = product.prep_station_ref_id or getattr(stations.get("bar"), "id", None)
        elif service_type == "internet":
            product.product_type = "internet"
            product.requires_preparation = False
            product.prep_station_ref_id = product.prep_station_ref_id or getattr(stations.get("service"), "id", None)
        elif item_type == "event_ticket":
            product.product_type = "event"
            product.requires_preparation = False
        elif item_type == "membership":
            product.product_type = "membership"
            product.requires_preparation = False
        elif item_type in {"service", "reservation"}:
            product.product_type = "service"
            product.requires_preparation = False
            product.prep_station_ref_id = product.prep_station_ref_id or getattr(stations.get("service"), "id", None)
        else:
            product.product_type = "other"
            product.requires_preparation = False
        product.save(update_fields=["product_type", "requires_preparation", "prep_station_ref", "updated_at"])

    for item in OrderItem.objects.select_related("product").all().iterator():
        product = item.product
        requires_prep = product.requires_preparation or product.product_type in {"food", "drink"}
        item.prep_station_id = item.prep_station_id or product.prep_station_ref_id or (getattr(stations.get("general"), "id", None) if requires_prep else None)
        if not requires_prep:
            item.prep_status = "no_prep"
        elif item.prep_status == "pending":
            item.prep_status = "new"
        item.save(update_fields=["prep_station", "prep_status", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_prepstation_options_prepstation_station_type"),
        ("core", "0009_order_cancellation_notes_order_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="prep_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.prepstation",
                verbose_name="محطة التحضير",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="orderable_on_pos",
            field=models.BooleanField(
                default=True, verbose_name="قابل للطلب من نقطة البيع"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("food", "طعام"),
                    ("drink", "مشروب"),
                    ("service", "خدمة"),
                    ("internet", "إنترنت"),
                    ("event", "فعالية"),
                    ("membership", "عضوية"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=20,
                verbose_name="نوع التشغيل",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_preparation",
            field=models.BooleanField(default=False, verbose_name="يحتاج تحضير"),
        ),
        migrations.AddField(
            model_name="product",
            name="visible_on_pos",
            field=models.BooleanField(default=True, verbose_name="ظاهر في نقطة البيع"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="prep_status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("sent", "مرسل للتحضير"),
                    ("accepted", "تم الاستلام"),
                    ("preparing", "قيد التحضير"),
                    ("ready", "جاهز"),
                    ("served", "تم التسليم"),
                    ("cancelled", "ملغى"),
                    ("no_prep", "لا يحتاج تحضير"),
                    ("pending", "جديد"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="prep_station_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.prepstation",
                verbose_name="محطة التحضير",
            ),
        ),
        migrations.RunPython(classify_products_and_items, migrations.RunPython.noop),
    ]
