# Generated by Django 5.2.15 on 2026-06-19 20:59

from django.db import migrations, models


def normalize_phase12e_data(apps, schema_editor):
    Order = apps.get_model("core", "Order")
    SystemSetting = apps.get_model("core", "SystemSetting")
    Order.objects.filter(fulfillment_mode="inside_space").update(fulfillment_mode="inside_space_general")
    Order.objects.filter(delivery_status="not_delivery").update(delivery_status="not_applicable")
    Order.objects.filter(delivery_status="delivery_requested").update(delivery_status="new")
    Order.objects.filter(delivery_status="ready_for_dispatch").update(delivery_status="ready_for_delivery")
    Order.objects.filter(delivery_status="failed").update(delivery_status="cancelled")
    for setting in SystemSetting.objects.all():
        setting.delivery_enabled = bool(getattr(setting, "enable_delivery", False))
        setting.takeaway_enabled = bool(getattr(setting, "enable_takeaway", False))
        setting.default_delivery_fee_syp = getattr(setting, "fixed_delivery_fee_syp", 0) or 0
        setting.require_delivery_address = getattr(setting, "require_address_for_delivery", True)
        setting.require_delivery_phone = getattr(setting, "require_phone_for_delivery", True)
        if getattr(setting, "default_fulfillment_mode", "") == "inside_space":
            setting.default_fulfillment_mode = "inside_space_general"
        setting.save(update_fields=["delivery_enabled", "takeaway_enabled", "default_delivery_fee_syp", "require_delivery_address", "require_delivery_phone", "default_fulfillment_mode"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_notificationevent_notificationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_to",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="مكلف بالتوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت إلغاء التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت تأكيد التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت إنشاء التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_customer_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="اسم زبون التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت تسليم التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_landmark",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="علامة قريبة"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_out_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت الخروج للتوصيل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="رقم هاتف التوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="allow_unpaid_delivery",
            field=models.BooleanField(
                default=True, verbose_name="السماح بطلبات توصيل غير مدفوعة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_delivery_fee_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="أجرة التوصيل الافتراضية"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="delivery_enabled",
            field=models.BooleanField(default=False, verbose_name="تفعيل التوصيل"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="require_delivery_address",
            field=models.BooleanField(
                default=True, verbose_name="العنوان مطلوب للتوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="require_delivery_phone",
            field=models.BooleanField(
                default=True, verbose_name="رقم الهاتف مطلوب للتوصيل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="takeaway_enabled",
            field=models.BooleanField(default=False, verbose_name="تفعيل السفري"),
        ),
        migrations.RunPython(normalize_phase12e_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "غير قابل للتطبيق"),
                    ("new", "جديد"),
                    ("confirmed", "مؤكد"),
                    ("preparing", "قيد التحضير"),
                    ("ready_for_delivery", "جاهز للتوصيل"),
                    ("out_for_delivery", "خرج للتوصيل"),
                    ("delivered", "تم التسليم"),
                    ("cancelled", "ملغى"),
                ],
                default="not_applicable",
                max_length=30,
                verbose_name="حالة التوصيل",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("inside_space_general", "طلب عام داخل المكان"),
                    ("table", "طاولة"),
                    ("delivery", "توصيل"),
                    ("takeaway", "تيك أواي"),
                ],
                default="inside_space_general",
                max_length=20,
                verbose_name="وضع الاستلام/التنفيذ",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="default_fulfillment_mode",
            field=models.CharField(
                choices=[
                    ("inside_space_general", "طلب عام داخل المكان"),
                    ("table", "طاولة"),
                    ("delivery", "توصيل"),
                    ("takeaway", "تيك أواي"),
                ],
                default="inside_space_general",
                max_length=20,
                verbose_name="وضع التنفيذ الافتراضي",
            ),
        ),
    ]
