# Generated by Django 5.2.15 on 2026-06-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_order_assigned_to_order_delivery_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetsession",
            name="billable_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="المدة المحسوبة"),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="سبب الإلغاء"),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="member_credit_used_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="رصيد العضو المستخدم"
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="member_minutes_used",
            field=models.PositiveIntegerField(
                default=0, verbose_name="دقائق العضو المستخدمة"
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="minimum_charge_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الحد الأدنى للدفع"
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="rounding_increment_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[(15, "15"), (30, "30"), (60, "60")],
                default=15,
                verbose_name="التقريب كل",
            ),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("internet", "إنترنت"),
                    ("workspace", "مساحة العمل"),
                    ("mixed", "إنترنت ومساحة عمل"),
                ],
                default="internet",
                max_length=20,
                verbose_name="نوع الجلسة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="allow_unpaid_sessions",
            field=models.BooleanField(
                default=True, verbose_name="السماح بجلسات غير مدفوعة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_minimum_charge_syp",
            field=models.PositiveIntegerField(
                default=0, verbose_name="الحد الأدنى للدفع"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_rounding_increment_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[(15, "15"), (30, "30"), (60, "60")],
                default=15,
                verbose_name="التقريب كل",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="default_workspace_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_setting_profiles",
                to="core.product",
                verbose_name="منتج مساحة العمل الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="internet_metered_enabled",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل المحاسبة حسب الوقت"
            ),
        ),
        migrations.AlterField(
            model_name="internetsession",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("prepaid", "مسبق الدفع"),
                    ("open_metered", "جلسة مفتوحة حسب الوقت"),
                    ("free", "مجاني"),
                    ("manual", "يدوي"),
                ],
                default="open_metered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internetsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعالة"),
                    ("ended", "منتهية"),
                    ("cancelled", "ملغاة"),
                    ("unpaid", "غير مدفوعة"),
                    ("billed", "مفروترة"),
                    ("paid", "مدفوعة"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="auto_create_order_for_metered_sessions",
            field=models.BooleanField(
                default=True, verbose_name="إنشاء طلب تلقائي للجلسات المحسوبة"
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="default_internet_billing_mode",
            field=models.CharField(
                choices=[
                    ("prepaid", "مسبق الدفع"),
                    ("open_metered", "جلسة مفتوحة حسب الوقت"),
                    ("free", "مجاني"),
                    ("manual", "يدوي"),
                ],
                default="open_metered",
                max_length=20,
                verbose_name="وضع فوترة الإنترنت الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="internet_service_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internet_setting_profiles",
                to="core.product",
                verbose_name="منتج الإنترنت الافتراضي",
            ),
        ),
    ]
