# Generated by Django 5.2.15 on 2026-06-19 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_internetsession_billable_minutes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="estimated_line_cost_syp_snapshot",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الكلفة التقديرية للسطر وقت البيع"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="estimated_line_margin_syp_snapshot",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="الهامش التقديري للسطر وقت البيع"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="estimated_unit_cost_syp_snapshot",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="كلفة الوحدة التقديرية وقت البيع"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الكلفة"),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر تحديث للكلفة"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_product_costs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="محدّث الكلفة",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="estimated_unit_cost_syp",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="الكلفة التقديرية"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="track_margin",
            field=models.BooleanField(default=True, verbose_name="تتبع الهامش"),
        ),
    ]
