# Generated by Django 5.2.15 on 2026-06-19 21:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('core', 'ExpenseCategory')
    defaults = [
        ('ingredients','مواد أولية','ingredients',10),('drinks_supplies','مشروبات ومستلزمات','drinks_supplies',20),('packaging','تغليف','packaging',30),('cleaning','تنظيف','cleaning',40),('utilities','كهرباء/مياه/خدمات','utilities',50),('maintenance','صيانة','maintenance',60),('transport','نقل','transport',70),('wages','أجور','wages',80),('event_cost','فعالية','event_cost',90),('equipment','معدات','equipment',100),('marketing','تسويق','marketing',110),('other','أخرى','other',120),
    ]
    for code, name, typ, order in defaults:
        ExpenseCategory.objects.update_or_create(code=code, defaults={'name_ar': name, 'category_type': typ, 'sort_order': order, 'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_display_on_pos_and_more"),
        ("core", "0014_orderitem_estimated_line_cost_syp_snapshot_and_more"),
        ("vendors", "0003_vendormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="تصنيف المصروف"),
                ),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("code", models.SlugField(max_length=80, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("ingredients", "مواد أولية"),
                            ("drinks_supplies", "مشروبات ومستلزمات"),
                            ("packaging", "تغليف"),
                            ("cleaning", "تنظيف"),
                            ("utilities", "كهرباء/مياه/خدمات"),
                            ("rent", "إيجار"),
                            ("maintenance", "صيانة"),
                            ("wages", "أجور"),
                            ("transport", "نقل"),
                            ("event_cost", "فعالية"),
                            ("equipment", "معدات"),
                            ("marketing", "تسويق"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="البائع/المورد"
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="مصروف")),
                ("description", models.TextField(blank=True)),
                (
                    "amount_syp",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "نقداً"),
                            ("card", "بطاقة"),
                            ("bank_transfer", "حوالة بنكية"),
                            ("mobile_transfer", "تحويل موبايل"),
                            ("credit", "آجل"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "paid_from",
                    models.CharField(
                        choices=[
                            ("cashbox", "الصندوق"),
                            ("owner", "المالك"),
                            ("bank", "البنك"),
                            ("external", "خارجي"),
                            ("unpaid", "غير مدفوع"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="مدفوع من",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("approved", "معتمد"),
                            ("paid", "مدفوع"),
                            ("cancelled", "ملغى"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="رقم الفاتورة"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_receipts",
                        to="catalog.mediaasset",
                        verbose_name="إيصال",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="vendors.vendor",
                        verbose_name="البائع/المورد",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="core.expensecategory",
                        verbose_name="تصنيف المصروف",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening_cash", "رصيد افتتاحي"),
                            ("owner_cash_in", "إدخال نقد من المالك"),
                            ("owner_cash_out", "سحب نقد من المالك"),
                            ("cash_expense", "مصروف نقدي"),
                            ("supplier_payment", "دفعة لمورد"),
                            ("cash_correction", "تصحيح نقدي"),
                            ("cash_deposit", "إيداع"),
                            ("cash_withdrawal", "سحب"),
                            ("refund", "استرجاع"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "دخول"), ("out", "خروج")], max_length=5
                    ),
                ),
                (
                    "amount_syp",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="المبلغ",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("notes", models.TextField(blank=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cash_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="core.order",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="core.payment",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "related_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="core.expense",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-created_at"],
            },
        ),
        migrations.RunPython(seed_expense_categories, migrations.RunPython.noop),
    ]
