# Generated by Django 5.2.15 on 2026-06-19 21:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_display_on_pos_and_more"),
        ("core", "0015_expensecategory_expense_cashmovement"),
        ("vendors", "0003_vendormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="auto_deduct_inventory_on_sale",
            field=models.BooleanField(
                default=False, verbose_name="خصم المخزون تلقائياً عند البيع"
            ),
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_ar",
                    models.CharField(max_length=160, verbose_name="مادة مخزون"),
                ),
                ("name_en", models.CharField(blank=True, max_length=160)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="SKU / Code",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ingredient", "مكوّن"),
                            ("drink_supply", "مشروبات ومستلزمات"),
                            ("packaging", "تغليف"),
                            ("cleaning", "تنظيف"),
                            ("equipment_consumable", "مستهلكات معدات"),
                            ("other", "أخرى"),
                        ],
                        default="ingredient",
                        max_length=30,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية الحالية",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="حد التنبيه",
                    ),
                ),
                (
                    "estimated_unit_cost_syp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكلفة التقديرية للوحدة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True)),
                (
                    "preferred_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_inventory_items",
                        to="vendors.vendor",
                        verbose_name="المورد المفضل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة مخزون",
                "verbose_name_plural": "مواد المخزون",
                "ordering": ["name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=160, verbose_name="المورد"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="رقم الفاتورة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("received", "مستلمة"),
                            ("partially_paid", "مدفوعة جزئياً"),
                            ("paid", "مدفوعة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقداً"),
                            ("card", "بطاقة"),
                            ("bank_transfer", "حوالة بنكية"),
                            ("mobile_transfer", "تحويل موبايل"),
                            ("credit", "آجل"),
                            ("other", "أخرى"),
                        ],
                        default="credit",
                        max_length=30,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "paid_from",
                    models.CharField(
                        choices=[
                            ("cashbox", "الصندوق"),
                            ("owner", "المالك"),
                            ("bank", "البنك"),
                            ("external", "خارجي"),
                            ("unpaid", "غير مدفوع"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="مدفوع من",
                    ),
                ),
                (
                    "subtotal_syp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_syp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_syp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_paid_syp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="المبلغ المدفوع",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_receipts",
                        to="catalog.mediaasset",
                        verbose_name="إيصال",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_purchases",
                        to="core.expense",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="vendors.vendor",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية شراء",
                "verbose_name_plural": "المشتريات",
                "ordering": ["-business_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "unit_cost_syp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "line_total_syp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="core.inventoryitem",
                        verbose_name="مادة مخزون",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند شراء",
                "verbose_name_plural": "بنود الشراء",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase_received", "استلام شراء"),
                            ("manual_adjustment", "تعديل يدوي"),
                            ("waste", "هدر"),
                            ("internal_use", "استخدام داخلي"),
                            ("return_to_vendor", "إرجاع للمورد"),
                            ("correction", "تصحيح"),
                            ("opening_balance", "رصيد افتتاحي"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "إدخال"), ("out", "إخراج")], max_length=5
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "unit_cost_syp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_value_syp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="سبب الحركة")),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="core.inventoryitem",
                        verbose_name="مادة مخزون",
                    ),
                ),
                (
                    "related_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="core.expense",
                    ),
                ),
                (
                    "related_purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="core.purchase",
                    ),
                ),
                (
                    "related_purchase_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="core.purchaseitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة مخزون",
                "verbose_name_plural": "حركات المخزون",
                "ordering": ["-business_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="الكمية لكل وحدة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_items",
                        to="core.inventoryitem",
                        verbose_name="مادة مستخدمة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_items",
                        to="core.product",
                        verbose_name="وصفة المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "وصفة المنتج",
                "verbose_name_plural": "وصفات المنتجات",
                "unique_together": {("product", "inventory_item", "unit")},
            },
        ),
    ]
