# Generated by Django 5.2.15 on 2026-06-19 21:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_systemsetting_auto_deduct_inventory_on_sale_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stock_deducted",
            field=models.BooleanField(default=False, verbose_name="تم خصم المخزون"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="stock_deducted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="وقت خصم المخزون"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="stock_deduction_error",
            field=models.TextField(blank=True, verbose_name="خطأ في خصم المخزون"),
        ),
        migrations.AddField(
            model_name="productrecipeitem",
            name="waste_factor_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="نسبة الهدر",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="core.order",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="related_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="core.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="stock_deduction_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "معطّل"),
                    ("on_order_created", "عند إنشاء الطلب"),
                    ("on_item_served", "عند تسليم العنصر"),
                    ("on_order_paid", "عند دفع الطلب"),
                ],
                default="disabled",
                max_length=30,
                verbose_name="وضع خصم المخزون",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="strict_stock_deduction",
            field=models.BooleanField(
                default=False, verbose_name="منع البيع عند نقص المخزون"
            ),
        ),
        migrations.AlterField(
            model_name="productrecipeitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="productrecipeitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الوصفة"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("purchase_received", "استلام شراء"),
                    ("manual_adjustment", "تعديل يدوي"),
                    ("waste", "هدر"),
                    ("internal_use", "استخدام داخلي"),
                    ("return_to_vendor", "إرجاع للمورد"),
                    ("correction", "تصحيح"),
                    ("opening_balance", "رصيد افتتاحي"),
                    ("sale_deduction", "خصم بيع"),
                    ("production_consumption", "استهلاك تحضير"),
                    ("production_output", "إنتاج تحضير"),
                    ("sale_return", "إرجاع خصم بيع"),
                    ("other", "أخرى"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="auto_deduct_inventory_on_sale",
            field=models.BooleanField(
                default=False, verbose_name="خصم المخزون عند البيع"
            ),
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_name_ar",
                    models.CharField(max_length=180, verbose_name="دفعة تحضير"),
                ),
                ("batch_name_en", models.CharField(blank=True, max_length=180)),
                ("business_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("prepared_food", "طعام محضر"),
                            ("drink_base", "أساس مشروب"),
                            ("sauce", "صلصة"),
                            ("mix", "خلطة"),
                            ("prep_component", "مكوّن تحضير"),
                            ("other", "أخرى"),
                        ],
                        default="prepared_food",
                        max_length=30,
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية المخططة",
                    ),
                ),
                (
                    "produced_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية المنتجة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("portion", "حصة"),
                            ("piece", "قطعة"),
                            ("tray", "صينية"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("other", "أخرى"),
                        ],
                        default="portion",
                        max_length=20,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "estimated_unit_cost_syp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكلفة التقديرية للوحدة",
                    ),
                ),
                (
                    "total_estimated_cost_syp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكلفة التقديرية الكلية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "مخططة"),
                            ("in_progress", "قيد التحضير"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ألغيت"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                (
                    "output_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="كمية الناتج",
                    ),
                ),
                (
                    "output_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="وحدة الناتج",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "output_inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="output_batches",
                        to="core.inventoryitem",
                        verbose_name="مادة مخزون ناتجة",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_batches",
                        to="core.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة تحضير",
                "verbose_name_plural": "دفعات التحضير",
                "ordering": ["-business_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="related_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="core.productionbatch",
            ),
        ),
        migrations.CreateModel(
            name="ProductionBatchIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية المخططة",
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية الفعلية",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "كغ"),
                            ("g", "غ"),
                            ("liter", "لتر"),
                            ("ml", "مل"),
                            ("piece", "قطعة"),
                            ("pack", "عبوة"),
                            ("bottle", "زجاجة"),
                            ("box", "صندوق"),
                            ("portion", "حصة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "estimated_unit_cost_syp_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_line_cost_syp_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="core.productionbatch",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_ingredients",
                        to="core.inventoryitem",
                        verbose_name="مكوّن",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكوّن دفعة تحضير",
                "verbose_name_plural": "مكوّنات دفعات التحضير",
            },
        ),
    ]
