# Generated by Django 5.2.15 on 2026-06-19 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_orderitem_stock_deducted_orderitem_stock_deducted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="print_default_template",
            field=models.CharField(
                choices=[("a4", "A4"), ("thermal", "حراري")],
                default="a4",
                max_length=20,
                verbose_name="قالب الطباعة الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="receipt_business_name",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="اسم المنشأة على الإيصال"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="receipt_footer_text",
            field=models.CharField(
                blank=True,
                default="شكراً لزيارتكم",
                max_length=240,
                verbose_name="نص أسفل الإيصال",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="receipt_show_logo",
            field=models.BooleanField(default=False, verbose_name="إظهار الشعار"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="receipt_show_qr",
            field=models.BooleanField(default=False, verbose_name="إظهار QR"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="thermal_receipt_width_mm",
            field=models.PositiveSmallIntegerField(
                default=80,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(110),
                ],
                verbose_name="عرض الإيصال الحراري",
            ),
        ),
    ]
