# Generated by Django 5.2.15 on 2026-06-20 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_display_on_pos_and_more"),
        ("core", "0018_receipt_print_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="border_radius",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32),
                ],
                verbose_name="استدارة الزوايا المختصرة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="brand_icon_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_icon_settings",
                to="catalog.mediaasset",
                verbose_name="الأيقونة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="brand_logo_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_logo_settings",
                to="catalog.mediaasset",
                verbose_name="الشعار",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="card_style",
            field=models.CharField(
                choices=[("soft", "ناعم"), ("flat", "مسطح"), ("bordered", "بحدود")],
                default="soft",
                max_length=20,
                verbose_name="نمط البطاقات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="mobile_product_density",
            field=models.CharField(
                choices=[("comfortable", "مريح"), ("compact", "مضغوط")],
                default="compact",
                max_length=20,
                verbose_name="كثافة العرض على الموبايل",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="pos_logo_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pos_logo_settings",
                to="catalog.mediaasset",
                verbose_name="شعار نقطة البيع",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="product_image_ratio",
            field=models.CharField(
                choices=[("1_1", "1:1"), ("4_3", "4:3"), ("3_2", "3:2")],
                default="4_3",
                max_length=10,
                verbose_name="نسبة صور المنتجات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="public_menu_banner_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_menu_banner_settings",
                to="catalog.mediaasset",
                verbose_name="بانر المنيو",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="public_menu_layout",
            field=models.CharField(
                choices=[
                    ("comfortable", "مريح"),
                    ("compact", "مضغوط"),
                    ("image_grid", "شبكة صور"),
                ],
                default="comfortable",
                max_length=20,
                verbose_name="تخطيط المنيو العام",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="public_menu_subtitle",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="وصف المنيو"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="public_menu_title",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="عنوان المنيو"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="receipt_logo_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_logo_settings",
                to="catalog.mediaasset",
                verbose_name="شعار الإيصال",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_banner_on_public_menu",
            field=models.BooleanField(default=True, verbose_name="إظهار بانر المنيو"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_product_descriptions_mobile",
            field=models.BooleanField(
                default=False, verbose_name="إظهار وصف المنتج على الموبايل"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="surface_color",
            field=models.CharField(
                default="#fffaf1",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون سطح البطاقات",
            ),
        ),
    ]
