# Generated by Django 5.2.15 on 2026-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_systemsetting_border_radius_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="public_menu_layout",
            field=models.CharField(
                choices=[
                    ("comfortable", "مريح / بطاقات كبيرة"),
                    ("compact", "مدمج"),
                    ("image_grid", "شبكة صور"),
                    ("compact_list", "قائمة تطبيق مدمجة"),
                ],
                default="comfortable",
                help_text="قائمة تطبيق مدمجة تعرض المنتجات كسطور صغيرة لتسهيل التصفح على الموبايل.",
                max_length=20,
                verbose_name="تخطيط المنيو العام",
            ),
        ),
    ]
