# Generated by Django 5.2.16 on 2026-07-18 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_systemsetting_public_menu_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashmovement",
            options={
                "ordering": ["-business_date", "-created_at"],
                "permissions": [
                    (
                        "add_cashmovement_staff",
                        "Can add cash movement from staff finance",
                    )
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="dailyclose",
            options={
                "permissions": [
                    ("view_finance_dashboard", "Can view finance dashboard"),
                    ("close_business_day", "Can close business day"),
                    ("reopen_business_day", "Can reopen business day"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-business_date", "-created_at"],
                "permissions": [
                    ("add_expense_staff", "Can add expense from staff finance")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ["-business_date", "-created_at"],
                "permissions": [("receive_purchase", "Can receive purchase")],
                "verbose_name": "عملية شراء",
                "verbose_name_plural": "المشتريات",
            },
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="reopen_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="reopened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="reopened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reopened_daily_closes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوح"),
                    ("closed", "مغلق"),
                    ("reopened", "أعيد فتحه"),
                ],
                default="closed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="invoice_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الفاتورة"
            ),
        ),
        migrations.CreateModel(
            name="DailyCloseRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_type", models.CharField(max_length=30)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_close_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "daily_close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="core.dailyclose",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
