# Generated by Django 5.2.16 on 2026-07-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_cashmovement_options_alter_dailyclose_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.member",
            ),
        ),
    ]
