# Generated by Django 5.2.16 on 2026-07-28 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_order_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="border_width_px",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="سماكة الحدود",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="button_radius_px",
            field=models.PositiveSmallIntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="استدارة الزر",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="control_height_px",
            field=models.PositiveSmallIntegerField(
                default=44,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="ارتفاع عناصر التحكم",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="danger_color",
            field=models.CharField(
                default="#b4232f",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون الخطر",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="enable_flat_shadows",
            field=models.BooleanField(
                default=False, verbose_name="تفعيل ظل وظيفي خفيف"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="font_fallback",
            field=models.CharField(
                choices=[
                    ("system", "خط النظام"),
                    ("arabic", "عربي حديث"),
                    ("classic", "عربي تقليدي"),
                ],
                default="arabic",
                max_length=20,
                verbose_name="الخط البديل",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="info_color",
            field=models.CharField(
                default="#27658a",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون المعلومات",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="line_height_percent",
            field=models.PositiveSmallIntegerField(
                default=155,
                validators=[
                    django.core.validators.MinValueValidator(130),
                    django.core.validators.MaxValueValidator(190),
                ],
                verbose_name="ارتفاع السطر (%)",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="panel_radius_px",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="استدارة اللوحة",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="secondary_surface_color",
            field=models.CharField(
                default="#f1ece3",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون السطح الثانوي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="show_interface_icons",
            field=models.BooleanField(
                default=True, verbose_name="إظهار الأيقونات في الواجهة"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="sidebar_width_px",
            field=models.PositiveSmallIntegerField(
                default=270,
                validators=[
                    django.core.validators.MinValueValidator(220),
                    django.core.validators.MaxValueValidator(360),
                ],
                verbose_name="عرض الشريط الجانبي",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="small_control_radius_px",
            field=models.PositiveSmallIntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="استدارة التحكم الصغير",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="sticky_header_enabled",
            field=models.BooleanField(default=False, verbose_name="تثبيت الهيدر"),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="success_color",
            field=models.CharField(
                default="#287a57",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون النجاح",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="warning_color",
            field=models.CharField(
                default="#9a650f",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="أدخل لوناً بصيغة HEX مثل #0f5f57 أو #fff.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="لون التحذير",
            ),
        ),
    ]
