# Generated by Django 5.2.17 on 2026-08-06 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SEEDED_ACCOUNTS = (
    ("cash:masharib", "نقد المشاريب", "Masharib cash", "asset", "masharib"),
    ("cash:sufra", "نقد السفرة", "Sufra cash", "asset", "sufra"),
    ("cash:events", "نقد الفعاليات", "Events cash", "asset", "events"),
    ("bank:main", "الحساب البنكي الرئيسي", "Main bank", "asset", ""),
    ("clearing:owner_paid", "مقاصة مدفوعات المالك", "Owner-paid clearing", "clearing", ""),
    ("payable:suppliers", "ذمم الموردين", "Supplier payables", "liability", ""),
    ("clearing:external", "المقاصة الخارجية", "External clearing", "clearing", ""),
)


def seed_financial_accounts(apps, schema_editor):
    """Create conservative defaults; deployments may explicitly resolve ownership."""
    FinancialAccount = apps.get_model("core", "FinancialAccount")
    overrides = getattr(settings, "FINANCIAL_ACCOUNT_SEED_OVERRIDES", {})
    for code, name_ar, name_en, account_type, suggested_unit in SEEDED_ACCOUNTS:
        configured = overrides.get(code, {})
        FinancialAccount.objects.get_or_create(
            code=code,
            defaults={
                "name_ar": configured.get("name_ar", name_ar),
                "name_en": configured.get("name_en", name_en),
                "account_type": configured.get("account_type", account_type),
                "scope": configured.get("scope", ""),
                "business_unit": configured.get("business_unit", suggested_unit),
                "is_active": configured.get("is_active", False),
                "currency": configured.get("currency", "SYP"),
                "negative_balance_policy": configured.get("negative_balance_policy", "forbid"),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0024_postingcommand_postingreconciliationfailure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name_ar", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                            ("clearing", "Clearing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope", models.CharField(blank=True, max_length=80)),
                ("business_unit", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=False)),
                ("currency", models.CharField(default="SYP", max_length=3)),
                (
                    "negative_balance_policy",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("warn", "Warn"),
                            ("forbid", "Forbid"),
                        ],
                        default="forbid",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=120)),
                ("source_object_id", models.CharField(blank=True, max_length=80)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "request_key",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correction_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_events",
                        to="core.auditevent",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_event",
                        to="core.auditevent",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostingBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_type", models.CharField(max_length=80)),
                (
                    "source_object_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("business_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending approval"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posting_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_posting_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="core.postingbatch",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "entry_role",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("tax", "Tax"),
                            ("fee", "Fee"),
                            ("discount", "Discount"),
                            ("rounding", "Rounding"),
                            ("clearing", "Clearing"),
                            ("other", "Other"),
                        ],
                        default="principal",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.financialaccount",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.postingbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("business_date", models.DateField()),
                (
                    "destination_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="core.financialaccount",
                    ),
                ),
                (
                    "posting_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer",
                        to="core.postingbatch",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="core.financialaccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="postingbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_content_type__isnull", True),
                        ("source_object_id__isnull", True),
                    ),
                    models.Q(
                        ("source_content_type__isnull", False),
                        ("source_object_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="posting_source_complete_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("posted_at__isnull", False),
                        ("reversed_at__isnull", True),
                        ("status", "posted"),
                    ),
                    models.Q(
                        ("posted_at__isnull", False),
                        ("reversed_at__isnull", False),
                        ("status", "reversed"),
                    ),
                    models.Q(
                        ("posted_at__isnull", True),
                        ("reversed_at__isnull", True),
                        ("status__in", ["draft", "pending", "cancelled"]),
                    ),
                    _connector="OR",
                ),
                name="posting_batch_valid_state_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reversal_of__isnull", True), ("status", "posted"), _connector="OR"
                ),
                name="posting_reversal_is_posted",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "posted"])),
                fields=("source_content_type", "source_object_id", "operation_type"),
                name="unique_active_posting_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("credit__isnull", True), ("debit__gt", 0)),
                    models.Q(("credit__gt", 0), ("debit__isnull", True)),
                    _connector="OR",
                ),
                name="posting_entry_one_positive_side",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transfer_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_account", models.F("destination_account")), _negated=True
                ),
                name="transfer_accounts_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("posting_batch__isnull", False),
                        ("state__in", ["posted", "reversed"]),
                    ),
                    models.Q(
                        ("posting_batch__isnull", True),
                        ("state__in", ["draft", "cancelled"]),
                    ),
                    _connector="OR",
                ),
                name="transfer_valid_state_batch",
            ),
        ),
        migrations.RunPython(seed_financial_accounts, migrations.RunPython.noop),
    ]
