# Generated by Django 5.2.17 on 2026-08-06 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_display_on_pos_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0025_additive_ledger_models"),
        ("vendors", "0003_vendormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_events",
                to="core.auditevent",
            ),
        ),
        migrations.AlterField(
            model_name="postingbatch",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversals",
                to="core.postingbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversal_of__isnull", False)),
                fields=("reversal_of",),
                name="unique_reversal_per_audit_event",
                violation_error_message="تم تسجيل عكس لهذا الحدث مسبقاً.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_syp__gt", 0)),
                name="cash_movement_amount_positive",
                violation_error_message="مبلغ حركة الصندوق يجب أن يكون موجباً.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["in", "out"])),
                name="cash_movement_direction_valid",
                violation_error_message="اتجاه حركة الصندوق غير صالح.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancellation_reason", ""), ("is_cancelled", False)),
                    models.Q(("cancellation_reason__gt", ""), ("is_cancelled", True)),
                    _connector="OR",
                ),
                name="cash_movement_cancel_fields_consistent",
                violation_error_message="حقول إلغاء حركة الصندوق غير متناسقة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_cancelled", False), ("related_expense__isnull", False)
                ),
                fields=("related_expense",),
                name="unique_active_expense_cash_movement",
                violation_error_message="يوجد بالفعل قيد صندوق نشط لهذا المصروف.",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_syp__gt", 0)),
                name="expense_amount_positive",
                violation_error_message="مبلغ المصروف يجب أن يكون موجباً.",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_syp__gt", 0)),
                name="payment_amount_positive",
                violation_error_message="مبلغ الدفعة يجب أن يكون موجباً.",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "method__in",
                        [
                            "cash",
                            "manual_transfer",
                            "unpaid",
                            "free",
                            "member_discount",
                        ],
                    )
                ),
                name="payment_method_valid",
                violation_error_message="طريقة الدفع غير صالحة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_reversed", False),
                        ("reversal_reason", ""),
                        ("reversed_at__isnull", True),
                        ("reversed_by__isnull", True),
                    ),
                    models.Q(
                        ("is_active", False),
                        ("is_reversed", True),
                        ("reversal_reason__gt", ""),
                        ("reversed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="payment_reversal_fields_consistent",
                violation_error_message="حقول عكس الدفعة غير متناسقة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversal_of__isnull", False)),
                fields=("reversal_of",),
                name="unique_reversal_per_posting_batch",
                violation_error_message="تم إنشاء عكس لهذا القيد مسبقاً.",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchase_item_quantity_positive",
                violation_error_message="كمية بند الشراء يجب أن تكون موجبة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_movement_quantity_positive",
                violation_error_message="كمية حركة المخزون يجب أن تكون موجبة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["in", "out"])),
                name="stock_movement_direction_valid",
                violation_error_message="اتجاه حركة المخزون غير صالح.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancellation_reason", ""), ("is_cancelled", False)),
                    models.Q(("cancellation_reason__gt", ""), ("is_cancelled", True)),
                    _connector="OR",
                ),
                name="stock_movement_cancel_fields_consistent",
                violation_error_message="حقول إلغاء حركة المخزون غير متناسقة.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_cancelled", False),
                    ("movement_type", "purchase_received"),
                    ("related_purchase_item__isnull", False),
                ),
                fields=("related_purchase_item",),
                name="unique_stock_receipt_per_purchase_line",
                violation_error_message="تم استلام بند الشراء هذا مسبقاً.",
            ),
        ),
    ]
