# Generated by Django 5.2.17 on 2026-08-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_expense_posting_fields(apps, schema_editor):
    Expense = apps.get_model('core', 'Expense')
    CashMovement = apps.get_model('core', 'CashMovement')
    FinancialAccount = apps.get_model('core', 'FinancialAccount')
    account_specs = {
        'cashbox': ('legacy.cashbox', 'الصندوق', 'cashbox'),
        'owner': ('legacy.owner', 'حساب المالك', 'owner'),
        'bank': ('legacy.bank', 'الحساب البنكي', 'bank'),
        'external': ('legacy.external', 'مصدر خارجي', 'external'),
    }
    accounts = {}
    for paid_from, (code, name, scope) in account_specs.items():
        accounts[paid_from], _ = FinancialAccount.objects.get_or_create(code=code, defaults={
            'name_ar': name, 'account_type': 'asset', 'scope': scope, 'is_active': True,
            'negative_balance_policy': 'allow',
        })
    for expense in Expense.objects.all().iterator():
        updates = {
            'payee_type': 'vendor' if expense.vendor_id else 'manual',
            'posting_state': ('cancelled' if expense.status == 'cancelled' else
                              'posted' if expense.status in {'approved', 'paid'} else 'draft'),
            'posting_version': 1 if expense.status in {'approved', 'paid'} else 0,
        }
        if expense.paid_from in accounts and expense.status == 'paid':
            updates['financial_account_id'] = accounts[expense.paid_from].pk
        Expense.objects.filter(pk=expense.pk).update(**updates)
    CashMovement.objects.filter(related_expense_id__isnull=False, movement_type='cash_expense').update(is_generated=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_auditevent_reversal_of_and_more"),
        ("vendors", "0003_vendormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cashmovement",
            name="unique_active_expense_cash_movement",
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="approval_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_expenses",
                to="core.postingbatch",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_expenses",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="liability_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liability_expenses",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_type",
            field=models.CharField(
                choices=[("vendor", "مورد مسجل"), ("manual", "مستفيد يدوي")],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paid_expenses",
                to="core.postingbatch",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="posting_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("posted", "Posted"),
                    ("reversed", "Reversed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="posting_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="expense",
            name="reversal_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_expenses",
                to="core.postingbatch",
            ),
        ),
        migrations.RunPython(backfill_expense_posting_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_cancelled", False),
                    ("is_generated", True),
                    ("related_expense__isnull", False),
                ),
                fields=("related_expense",),
                name="unique_active_generated_expense_cash_movement",
                violation_error_message="يوجد بالفعل قيد صندوق مولد نشط لهذا المصروف.",
            ),
        ),
    ]
