# Generated by Django 5.2.17 on 2026-08-07 00:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_purchase_payments(apps, schema_editor):
    Purchase = apps.get_model("core", "Purchase")
    PurchasePayment = apps.get_model("core", "PurchasePayment")
    PostingBatch = apps.get_model("core", "PostingBatch")
    PostingEntry = apps.get_model("core", "PostingEntry")
    FinancialAccount = apps.get_model("core", "FinancialAccount")
    ContentType = apps.get_model("contenttypes", "ContentType")
    account, _ = FinancialAccount.objects.get_or_create(
        code="clearing:legacy_purchase_payments",
        defaults={"name_ar": "مدفوعات مشتريات مرحّلة", "name_en": "Legacy purchase payments",
                  "account_type": "clearing", "is_active": False, "negative_balance_policy": "allow"})
    payable, _ = FinancialAccount.objects.get_or_create(
        code="payable:suppliers", defaults={"name_ar": "ذمم الموردين", "name_en": "Supplier payables",
        "account_type": "liability", "is_active": False, "negative_balance_policy": "allow"})
    content_type = ContentType.objects.get_for_model(Purchase)
    for purchase in Purchase.objects.exclude(amount_paid_syp=0).iterator():
        key = f"purchase:{purchase.pk}:legacy-payment"
        batch = PostingBatch.objects.create(
            operation_type="purchase.payment.backfill", source_content_type=content_type,
            source_object_id=str(purchase.pk), business_date=purchase.business_date, status="posted",
            idempotency_key=f"{key}:batch", actor_id=purchase.created_by_id, posted_at=timezone.now(),
            metadata={"legacy_amount_paid_syp": str(purchase.amount_paid_syp)})
        PurchasePayment.objects.create(
            purchase_id=purchase.pk, amount_syp=purchase.amount_paid_syp, source_account=account,
            actor_id=purchase.created_by_id, approver_id=purchase.approved_by_id,
            business_date=purchase.business_date, idempotency_key=key, posting_batch=batch)
        PostingEntry.objects.bulk_create([
            PostingEntry(batch=batch, account=payable, debit=purchase.amount_paid_syp),
            PostingEntry(batch=batch, account=account, credit=purchase.amount_paid_syp),
        ])


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0027_remove_cashmovement_unique_active_expense_cash_movement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount_syp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("business_date", models.DateField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "returned_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="stockmovement",
            name="unique_stock_receipt_per_purchase_line",
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_purchase_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="posting_batch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_payment",
                to="core.postingbatch",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="reversal_batch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_purchase_payment",
                to="core.postingbatch",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_payments",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="core.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_purchase_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiptline",
            name="purchase_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="core.purchaseitem",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceiptline",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="core.purchasereceipt",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="purchase_receipt_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement",
                to="core.purchasereceiptline",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="core.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnline",
            name="purchase_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_lines",
                to="core.purchaseitem",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnline",
            name="purchase_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="core.purchasereturn",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnline",
            name="receipt_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_lines",
                to="core.purchasereceiptline",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="purchase_return_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movement",
                to="core.purchasereturnline",
            ),
        ),
        migrations.RunPython(backfill_purchase_payments, migrations.RunPython.noop),
        migrations.RemoveField(model_name="purchase", name="amount_paid_syp"),
        migrations.AddConstraint(
            model_name="purchasereceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "purchase_item"),
                name="unique_purchase_item_per_receipt",
            ),
        ),
    ]
