# Generated by Django 5.2.17 on 2026-08-07 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_purchase_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyclose",
            name="unique_finalized_daily_close_per_date",
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="period_closes",
                to="core.financialaccount",
                verbose_name="الحساب المالي",
            ),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_daily_closes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyclose",
            name="close_snapshot",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="shift",
            name="cashbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="counted_amount_syp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_amount_syp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyclose",
            name="business_date",
            field=models.DateField(verbose_name="تاريخ العمل"),
        ),
        migrations.AlterField(
            model_name="dailyclose",
            name="expected_cash_syp",
            field=models.IntegerField(default=0, verbose_name="النقد المتوقع"),
        ),
        migrations.AlterField(
            model_name="dailyclose",
            name="opening_cash_syp",
            field=models.IntegerField(default=0, verbose_name="النقد الافتتاحي"),
        ),
        migrations.AddConstraint(
            model_name="dailyclose",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_finalized", True)),
                fields=("account", "business_date"),
                name="unique_active_close_per_account_date",
            ),
        ),
    ]
