# Generated by Django 5.2.17 on 2026-08-07 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_purchase_lifecycle"),
        ("vendors", "0003_vendormedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movement_projections",
                to="core.financialaccount",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_projections",
                to="core.transfer",
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="transfer_leg",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="transfer",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="reversal_batch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_transfer",
                to="core.postingbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transfer__isnull", False)),
                fields=("transfer", "transfer_leg"),
                name="unique_transfer_movement_leg",
            ),
        ),
    ]
