# Generated by Django 5.2.17 on 2026-08-07 00:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_cashmovement_financial_account_cashmovement_transfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashmovement",
            name="amount_syp",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="المبلغ",
            ),
        ),
    ]
