# Generated by Django 5.2.17 on 2026-08-07 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_finance_reconciliation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashmovement",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movement_projections",
                to="core.financialaccount",
            ),
        ),
    ]
