# Generated by Django 5.2.17 on 2026-08-07 12:37

import django.db.models.deletion
import datetime
from decimal import Decimal


def initial_usd_rate(apps, schema_editor):
    apps.get_model('core', 'ExchangeRate').objects.get_or_create(
        foreign_currency='USD', effective_date=datetime.date(2025, 1, 1),
        defaults={'base_currency': 'SYP_NEW', 'rate_to_base': Decimal('130'),
                  'source': 'سعر افتتاحي قابل للتحديث'},
    )
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0033_seed_unconfirmed_finance_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_currency",
                    models.CharField(default="SYP_NEW", editable=False, max_length=8),
                ),
                ("foreign_currency", models.CharField(default="USD", max_length=8)),
                ("rate_to_base", models.DecimalField(decimal_places=8, max_digits=20)),
                ("effective_date", models.DateField(db_index=True)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_exchange_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="core.exchangerate",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
                "permissions": [
                    ("view_exchange_rates", "Can view exchange rates"),
                    ("create_today_exchange_rate", "Can create today's exchange rate"),
                    ("correct_exchange_rate", "Can supersede an exchange rate"),
                    ("use_stale_exchange_rate", "Can use a stale exchange rate"),
                    ("approve_high_risk_amount", "Can approve high-risk amounts"),
                    ("perform_currency_conversion", "Can perform currency conversions"),
                    ("view_usd_balances", "Can view USD balances"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurrencyEntrySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_object_id", models.CharField(max_length=80)),
                ("operation", models.CharField(max_length=60)),
                ("field_name", models.CharField(max_length=80)),
                (
                    "transaction_currency",
                    models.CharField(default="SYP_NEW", max_length=8),
                ),
                (
                    "settlement_currency",
                    models.CharField(default="SYP_NEW", max_length=8),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "exchange_rate_to_base",
                    models.DecimalField(decimal_places=8, default=1, max_digits=20),
                ),
                (
                    "base_amount_syp",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("rate_effective_date", models.DateField(blank=True, null=True)),
                ("rate_source_snapshot", models.CharField(blank=True, max_length=200)),
                ("rate_selected_automatically", models.BooleanField(default=True)),
                ("risk_level", models.CharField(default="normal", max_length=32)),
                ("risk_reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "suggested_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "equivalent_old_syp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                ("thresholds_applied", models.JSONField(blank=True, default=dict)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_currency_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_currency_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "exchange_rate_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.exchangerate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_to_base__gte", 1)),
                name="exchange_rate_not_reciprocal",
            ),
        ),
        migrations.AddConstraint(
            model_name="currencyentrysnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_content_type",
                    "source_object_id",
                    "operation",
                    "field_name",
                ),
                name="one_currency_snapshot_per_source_field",
            ),
        ),
        migrations.RunPython(initial_usd_rate, migrations.RunPython.noop),
    ]
