# Generated by Django 5.2.17 on 2026-08-10 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_package_duration(apps, schema_editor):
    Package = apps.get_model('core', 'InternetPackage')
    Package.objects.filter(session_minutes_limit__isnull=True).update(session_minutes_limit=models.F('duration_minutes'))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_currency_safety"),
        ("members", "0002_memberactivationtoken_memberdevicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternetBandwidthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "download_limit_kbps",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "upload_limit_kbps",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternetPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("active", models.BooleanField(default=True)),
                (
                    "revenue_share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("timed_session", "جلسة محددة الوقت"),
                    ("validity_pass", "بطاقة صلاحية"),
                    ("allowance", "رصيد دقائق"),
                    ("unlimited", "غير محدود"),
                    ("membership_credit", "رصيد العضوية"),
                ],
                default="timed_session",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="activation_policy",
            field=models.CharField(
                choices=[
                    ("on_purchase", "عند الشراء"),
                    ("on_first_use", "عند أول استخدام"),
                    ("manual", "يدوي"),
                ],
                default="on_purchase",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="backend_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="code",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="daily_minutes_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="guest_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="max_concurrent_devices",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="max_registered_devices",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="member_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="partner_share_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="session_minutes_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="total_minutes_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="validity_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minutes", "دقيقة"),
                    ("days", "يوم"),
                    ("weeks", "أسبوع"),
                    ("months", "شهر"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="validity_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="visible_to_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="visible_to_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="internetpackage",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="bandwidth_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="core.internetbandwidthprofile",
            ),
        ),
        migrations.CreateModel(
            name="InternetEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("guest_name", models.CharField(blank=True, max_length=120)),
                ("guest_phone", models.CharField(blank=True, max_length=30)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "access_code",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار التفعيل"),
                            ("active", "فعال"),
                            ("expired", "منتهي"),
                            ("cancelled", "ملغى"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("timed_session", "جلسة محددة الوقت"),
                            ("validity_pass", "بطاقة صلاحية"),
                            ("allowance", "رصيد دقائق"),
                            ("unlimited", "غير محدود"),
                            ("membership_credit", "رصيد العضوية"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "activation_policy",
                    models.CharField(
                        choices=[
                            ("on_purchase", "عند الشراء"),
                            ("on_first_use", "عند أول استخدام"),
                            ("manual", "يدوي"),
                        ],
                        max_length=24,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("validity_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "validity_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "دقيقة"),
                            ("days", "يوم"),
                            ("weeks", "أسبوع"),
                            ("months", "شهر"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "session_minutes_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_minutes_allowed",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("minutes_used", models.PositiveIntegerField(default=0)),
                (
                    "daily_minutes_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("bandwidth_profile_code", models.CharField(blank=True, max_length=50)),
                ("max_concurrent_devices", models.PositiveSmallIntegerField(default=1)),
                ("max_registered_devices", models.PositiveSmallIntegerField(default=1)),
                ("network_backend", models.CharField(default="manual", max_length=30)),
                (
                    "network_status",
                    models.CharField(
                        choices=[
                            ("not_provisioned", "غير مجهز"),
                            ("provisioned", "مجهز"),
                            ("disconnected", "مفصول"),
                            ("provision_error", "خطأ تجهيز"),
                        ],
                        default="not_provisioned",
                        max_length=30,
                    ),
                ),
                (
                    "external_network_identifier",
                    models.CharField(blank=True, max_length=120),
                ),
                ("last_network_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_network_error", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "gross_amount_syp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_internet_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_internet_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internet_entitlements",
                        to="core.member",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internet_entitlements",
                        to="core.order",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="core.internetpackage",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internet_entitlements",
                        to="core.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internet_entitlements",
                        to="members.membershipsubscription",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="core.internetpartner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="internetsession",
            name="entitlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="core.internetentitlement",
            ),
        ),
        migrations.AddField(
            model_name="internetpackage",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="core.internetpartner",
            ),
        ),
        migrations.CreateModel(
            name="InternetPartnerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_view_customer_phone", models.BooleanField(default=False)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.internetpartner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="internetpartner",
            name="users",
            field=models.ManyToManyField(
                related_name="internet_partners",
                through="core.InternetPartnerUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="InternetRevenueShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gross_amount_syp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("share_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "partner_amount_syp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "hub_amount_syp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("business_date", models.DateField()),
                (
                    "entitlement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_share",
                        to="core.internetentitlement",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.order",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_shares",
                        to="core.internetpackage",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_shares",
                        to="core.internetpartner",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternetAccessDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_mac", models.CharField(max_length=64)),
                ("nickname", models.CharField(blank=True, max_length=120)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "entitlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="core.internetentitlement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entitlement", "device_mac"),
                        name="unique_entitlement_device",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="internetpartneruser",
            constraint=models.UniqueConstraint(
                fields=("partner", "user"), name="unique_internet_partner_user"
            ),
        ),
        migrations.RunPython(preserve_legacy_package_duration, migrations.RunPython.noop),
    ]
