# Generated by Django 5.2.17 on 2026-08-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_internetbandwidthprofile_internetpartner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetsession",
            name="allowance_minutes_consumed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InternetRevenueShareAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reversal", "عكس"),
                            ("refund", "استرداد"),
                            ("correction", "تصحيح"),
                        ],
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                (
                    "gross_delta_syp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "partner_delta_syp",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("hub_delta_syp", models.DecimalField(decimal_places=2, max_digits=14)),
                ("business_date", models.DateField()),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.payment",
                    ),
                ),
                (
                    "revenue_share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="core.internetrevenueshare",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
