# Generated by Django 5.2.17 on 2026-08-11 16:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_mikrotik_network_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internetpartner",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="internetpackage",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="ترك الحقل فارغاً يعني استخدام شريك الإنترنت الافتراضي.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="core.internetpartner",
                verbose_name="شريك إنترنت خاص بهذه الباقة (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="internetpackage",
            name="partner_share_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ترك الحقل فارغاً يعني استخدام النسبة الافتراضية للشريك الفعلي.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="نسبة مشاركة خاصة بهذه الباقة (اختياري)",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetpartner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_default", False), ("active", True), _connector="OR"
                ),
                name="internet_partner_default_must_be_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetpartner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_internet_partner",
            ),
        ),
    ]
