# Generated by Django 5.2.17 on 2026-08-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_internetpartner_is_default_and_more"),
        ("members", "0004_add_membership_benefits_and_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetentitlement",
            name="origin_type",
            field=models.CharField(default="direct_package", max_length=30),
        ),
        migrations.AddField(
            model_name="internetentitlement",
            name="partner_name_snapshot",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="internetentitlement",
            name="partner_share_percent_snapshot",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="internetentitlement",
            name="source_benefit_rule_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetrevenueshare",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internet_revenue_shares",
                to="members.membershipsubscription",
            ),
        ),
        migrations.AlterField(
            model_name="internetentitlement",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entitlements",
                to="core.internetpackage",
            ),
        ),
        migrations.AlterField(
            model_name="internetrevenueshare",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenue_shares",
                to="core.internetpackage",
            ),
        ),
    ]
