# Generated by Django 5.2.17 on 2026-08-12 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_internetentitlement_origin_type_and_more"),
        ("members", "0005_membershipbenefitrule_commercial_allocation_syp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternetUsageLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField()),
                ("minutes", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="internetsession",
            name="authorized_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="authorized_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="overrun_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="reservation_business_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="reserved_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="internetentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_minutes_allowed__isnull", True),
                    ("minutes_used__lte", models.F("total_minutes_allowed")),
                    _connector="OR",
                ),
                name="internet_minutes_used_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_minutes__gte", 0)),
                name="internet_session_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("authorized_minutes__gte", 0)),
                name="internet_session_authorized_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("overrun_minutes__gte", 0)),
                name="internet_session_overrun_nonnegative",
            ),
        ),
        migrations.AddField(
            model_name="internetusageledger",
            name="entitlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usage_ledger",
                to="core.internetentitlement",
            ),
        ),
        migrations.AddField(
            model_name="internetusageledger",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usage_ledger",
                to="core.internetsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetusageledger",
            constraint=models.UniqueConstraint(
                fields=("session", "business_date"),
                name="unique_internet_session_usage_day",
            ),
        ),
    ]
