# Generated by Django 5.2.17 on 2026-08-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_internetnetworkoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="internetentitlement",
            name="lifecycle_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="internetsession",
            name="lifecycle_end_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="internetentitlement", name="status",
            field=models.CharField(choices=[("pending", "بانتظار التفعيل"), ("active", "فعال"),
                ("expired", "منتهي"), ("cancelled", "ملغى"), ("suspended", "معلّق")],
                default="pending", max_length=20),
        ),
    ]
