# Generated by Django 5.2.17 on 2026-08-13 00:08

import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def preflight_and_snapshot(apps, schema_editor):
    """Refuse conflicting/invalid history; only canonicalize non-financial MAC data."""
    from collections import defaultdict
    from decimal import Decimal
    import re

    Device = apps.get_model('core', 'InternetAccessDevice')
    Entitlement = apps.get_model('core', 'InternetEntitlement')
    Partner = apps.get_model('core', 'InternetPartner')
    Package = apps.get_model('core', 'InternetPackage')
    Share = apps.get_model('core', 'InternetRevenueShare')
    failures = []
    seen = defaultdict(list)
    normalized = {}
    for device in Device.objects.all().only('pk', 'entitlement_id', 'device_mac'):
        compact = re.sub(r'[:-]', '', (device.device_mac or '').strip())
        if not re.fullmatch(r'[0-9A-Fa-f]{12}', compact):
            failures.append(f'device {device.pk} has malformed MAC')
            continue
        canonical = ':'.join(compact.upper()[i:i + 2] for i in range(0, 12, 2))
        seen[(device.entitlement_id, canonical)].append(device.pk)
        normalized[device.pk] = canonical
    failures.extend(f'duplicate device identity {key}: rows {ids}'
                    for key, ids in seen.items() if len(ids) > 1)
    failures.extend(f'entitlement {row.pk} has invalid commercial values'
                    for row in Entitlement.objects.exclude(gross_amount_syp__gte=0))
    failures.extend(f'entitlement {row.pk} has invalid partner percentage'
                    for row in Entitlement.objects.exclude(partner_share_percent_snapshot__isnull=True)
                    .exclude(partner_share_percent_snapshot__range=(0, 100)))
    failures.extend(f'partner {row.pk} has invalid percentage'
                    for row in Partner.objects.exclude(revenue_share_percent__range=(0, 100)))
    failures.extend(f'package {row.pk} has invalid percentage'
                    for row in Package.objects.exclude(partner_share_percent__isnull=True)
                    .exclude(partner_share_percent__range=(0, 100)))
    for share in Share.objects.select_related('entitlement'):
        if (share.share_percent < 0 or share.share_percent > 100 or
                min(share.gross_amount_syp, share.partner_amount_syp, share.hub_amount_syp) < 0 or
                Decimal(share.partner_amount_syp) + Decimal(share.hub_amount_syp) != Decimal(share.gross_amount_syp)):
            failures.append(f'revenue share {share.pk} violates commercial arithmetic')
    if failures:
        raise RuntimeError('Internet invariant migration preflight failed; no history was changed: ' + '; '.join(failures[:20]))
    for pk, canonical in normalized.items():
        Device.objects.filter(pk=pk).update(device_mac=canonical)
    # The linked entitlement is the strongest existing historical name source.
    for share in Share.objects.filter(partner_name_snapshot='').select_related('entitlement'):
        if share.entitlement.partner_name_snapshot:
            Share.objects.filter(pk=share.pk, partner_name_snapshot='').update(
                partner_name_snapshot=share.entitlement.partner_name_snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_internetentitlement_lifecycle_reason_and_more"),
        ("members", "0008_membershipsubscription_total_frozen_duration_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internetentitlement",
            name="sale_request_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="internetrevenueshare",
            name="partner_name_snapshot",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(preflight_and_snapshot, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="internetaccessdevice",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("device_mac"),
                models.F("entitlement"),
                name="unique_entitlement_device_mac_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_amount_syp__gte", 0)),
                name="internet_entitlement_gross_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partner_share_percent_snapshot__isnull", True),
                    models.Q(
                        ("partner_share_percent_snapshot__gte", 0),
                        ("partner_share_percent_snapshot__lte", 100),
                    ),
                    _connector="OR",
                ),
                name="internet_entitlement_share_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partner_share_percent__isnull", True),
                    models.Q(("partner_share_percent__gte", 0), ("partner_share_percent__lte", 100)),
                    _connector="OR",
                ),
                name="internet_package_share_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetpartner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revenue_share_percent__gte", 0),
                    ("revenue_share_percent__lte", 100),
                ),
                name="internet_partner_share_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetrevenueshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("share_percent__gte", 0), ("share_percent__lte", 100)
                ),
                name="internet_revenue_share_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetrevenueshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_amount_syp__gte", 0)),
                name="internet_revenue_share_gross_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetrevenueshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("partner_amount_syp__gte", 0)),
                name="internet_revenue_share_partner_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetrevenueshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("hub_amount_syp__gte", 0)),
                name="internet_revenue_share_hub_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internetrevenueshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "partner_amount_syp",
                        django.db.models.expressions.CombinedExpression(
                            models.F("gross_amount_syp"),
                            "-",
                            models.F("hub_amount_syp"),
                        ),
                    )
                ),
                name="internet_revenue_share_arithmetic",
            ),
        ),
    ]
