# Generated by Django 5.2.17 on 2026-09-03 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productmedia_display_on_pos_and_more'),
        ('core', '0046_operationsimportreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('webpush', 'Web Push')], default='webpush', max_length=20)),
                ('endpoint', models.TextField()),
                ('endpoint_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('p256dh', models.TextField()),
                ('auth_secret', models.TextField()),
                ('device_label', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('permission_state', models.CharField(choices=[('granted', 'Granted'), ('prompt', 'Prompt'), ('denied', 'Denied')], default='granted', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='push_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='core.pushsubscription'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'status', 'next_attempt_at'], name='core_notifi_channel_9136ee_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['push_subscription', 'created_at'], name='core_notifi_push_su_fc5d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('push_subscription__isnull', False), models.Q(('dedupe_key', ''), _negated=True)), fields=('push_subscription', 'channel', 'dedupe_key'), name='uniq_push_delivery_dedupe'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active', 'last_seen_at'], name='core_pushsu_user_id_d4e1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['provider', 'is_active'], name='core_pushsu_provide_8c9c94_idx'),
        ),
    ]
