# Generated by Django 5.2.17 on 2026-08-12 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_internetentitlement_origin_type_and_more"),
        ("events", "0003_event_room"),
        ("reservations", "0002_reservation_workflows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["reservation_date", "start_time", "end_time", "status"],
                name="reservation_interval_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["event", "status"], name="reservation_event_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True),
                    ("start_time__isnull", True),
                    ("end_time__gt", models.F("start_time")),
                    _connector="OR",
                ),
                name="reservation_end_after_start",
            ),
        ),
    ]
