# Generated by Django 5.2.17 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_operationsimportreceipt'),
        ('reservations', '0003_reservation_reservation_interval_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='visit',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reservation',
                to='core.hubvisit',
            ),
        ),
    ]
