from django.contrib import admin
from django.urls import path
from core.views import (
    dashboard,
    menu_public,
    menu_table,
    order_public,
    staff_home,
    staff_qr_links,
    staff_qr_print,
    staff_menu_tools,
    staff_orders,
    staff_order_status,
    staff_cashier,
    staff_cashier_order,
    staff_cashier_pay,
    staff_reports_home,
    staff_reports_day,
    staff_reports_day_csv,
    staff_close_day,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('menu/', menu_public, name='menu_public'),
    path('menu/table/<uuid:qr_token>/', menu_table, name='menu_table'),
    path('order/<uuid:public_code>/', order_public, name='order_public'),
    path('staff/', staff_home, name='staff_home'),
    path('staff/qr/', staff_qr_links, name='staff_qr_links'),
    path('staff/qr/print/', staff_qr_print, name='staff_qr_print'),
    path('staff/menu-tools/', staff_menu_tools, name='staff_menu_tools'),
    path('staff/orders/', staff_orders, name='staff_orders'),
    path('staff/orders/partial/', staff_orders, name='staff_orders_partial'),
    path('staff/orders/<uuid:public_code>/status/', staff_order_status, name='staff_order_status'),
    path('staff/cashier/', staff_cashier, name='staff_cashier'),
    path('staff/cashier/<uuid:public_code>/', staff_cashier_order, name='staff_cashier_order'),
    path('staff/cashier/<uuid:public_code>/pay/', staff_cashier_pay, name='staff_cashier_pay'),
    path('staff/reports/', staff_reports_home, name='staff_reports_home'),
    path('staff/reports/day/', staff_reports_day, name='staff_reports_day'),
    path('staff/reports/day.csv', staff_reports_day_csv, name='staff_reports_day_csv'),
    path('staff/close-day/', staff_close_day, name='staff_close_day'),
]
