# Generated by Django 5.2.14 on 2026-05-28 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("core", "0003_orderitem_item_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.SlugField(unique=True)),
                ("name_ar", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[("single", "Single"), ("multiple", "Multiple")],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("min_selected", models.PositiveIntegerField(default=0)),
                ("max_selected", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.SlugField()),
                ("name_ar", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("price_delta_syp", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.productoptiongroup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name_ar"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "code"), name="unique_option_code_per_group"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionGroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_assignments",
                        to="catalog.productoptiongroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_group_assignments",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "group__sort_order", "group__name_ar"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "group"),
                        name="unique_option_group_per_product",
                    )
                ],
            },
        ),
    ]
