# Generated by Django 5.2.14 on 2026-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productoptiongroup_productoption_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "ordering": ["sort_order", "name_ar"],
                "verbose_name": "خيارات المنتجات",
                "verbose_name_plural": "خيارات المنتجات",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptiongroup",
            options={
                "ordering": ["sort_order", "name_ar"],
                "verbose_name": "مجموعات خيارات المنتجات",
                "verbose_name_plural": "مجموعات خيارات المنتجات",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptiongroupassignment",
            options={
                "ordering": ["sort_order", "group__sort_order", "group__name_ar"],
                "verbose_name": "ربط الخيارات بالمنتجات",
                "verbose_name_plural": "ربط الخيارات بالمنتجات",
            },
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="applies_to_beverage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coffee", "Coffee"),
                    ("tea", "Tea"),
                    ("mate", "Mate"),
                    ("juice", "Juice"),
                    ("zhourat", "Zhourat"),
                    ("local", "Local"),
                    ("arak", "Arak"),
                    ("wine", "Wine"),
                    ("beer", "Beer"),
                    ("cocktail", "Cocktail"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="نوع المشروب",
            ),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="applies_to_food_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hub_food", "Hub Food"),
                    ("vendor_food", "Vendor Food"),
                    ("guest_chef", "Guest Chef"),
                    ("snack", "Snack"),
                    ("daily_dish", "Daily Dish"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="نوع الطعام",
            ),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="applies_to_item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beverage", "Beverage"),
                    ("food", "Food"),
                    ("service", "Service"),
                    ("event_ticket", "Event Ticket"),
                    ("reservation", "Reservation"),
                    ("membership", "Membership"),
                    ("retail", "Retail"),
                    ("addon", "Addon"),
                ],
                max_length=30,
                verbose_name="نوع المنتج",
            ),
        ),
        migrations.AddField(
            model_name="productoptiongroup",
            name="applies_to_service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internet", "Internet"),
                    ("workspace", "Workspace"),
                    ("table_reservation", "Table Reservation"),
                    ("room_booking", "Room Booking"),
                    ("workshop", "Workshop"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="نوع الخدمة",
            ),
        ),
    ]
