# Generated by Django 5.2.14 on 2026-05-29 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_option_group_applicability_data"),
        ("core", "0003_orderitem_item_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "Animated GIF"),
                            ("external_url", "External URL"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("alt_text_ar", models.CharField(blank=True, max_length=180)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "وسائط المنتج",
                "verbose_name_plural": "وسائط المنتجات",
                "ordering": ["sort_order", "-is_primary", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "is_primary", "sort_order"],
                        name="catalog_pro_product_a0c953_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_primary", True)),
                        fields=("product",),
                        name="unique_active_primary_product_media",
                    )
                ],
            },
        ),
    ]
