# Generated by Django 5.2.15 on 2026-06-19 20:25

from django.db import migrations, models




def seed_default_prep_stations(apps, schema_editor):
    PrepStation = apps.get_model("catalog", "PrepStation")
    defaults = [
        ("kitchen", "المطبخ", "Kitchen", "kitchen", 10),
        ("bar", "البار", "Bar", "bar", 20),
        ("cashier", "الكاشير", "Cashier", "cashier", 30),
        ("service", "الخدمات", "Service", "service", 40),
        ("general", "عام", "General", "general", 50),
    ]
    for code, name_ar, name_en, station_type, sort_order in defaults:
        PrepStation.objects.update_or_create(
            code=code,
            defaults={
                "name_ar": name_ar,
                "name_en": name_en,
                "station_type": station_type,
                "is_active": True,
                "sort_order": sort_order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prepstation",
            options={
                "ordering": ["sort_order", "name_ar"],
                "verbose_name": "محطة التحضير",
                "verbose_name_plural": "محطات التحضير",
            },
        ),
        migrations.AddField(
            model_name="prepstation",
            name="station_type",
            field=models.CharField(
                choices=[
                    ("kitchen", "المطبخ"),
                    ("bar", "البار"),
                    ("cashier", "الكاشير"),
                    ("service", "الخدمات"),
                    ("general", "عام"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_default_prep_stations, migrations.RunPython.noop),
    ]
