# Generated by Django 5.2.15 on 2026-06-19 20:50

import catalog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_prepstation_options_prepstation_station_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="display_on_pos",
            field=models.BooleanField(default=True, verbose_name="إظهار في نقطة البيع"),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="display_on_public_menu",
            field=models.BooleanField(
                default=True, verbose_name="إظهار في المنيو العام"
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title_ar", models.CharField(max_length=180, verbose_name="العنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="العنوان بالإنجليزية"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=catalog.models.media_asset_upload_path,
                        validators=[catalog.models.validate_media_asset_file],
                        verbose_name="رفع صورة",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="رابط خارجي"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("gif", "صورة متحركة"),
                            ("video", "فيديو"),
                            ("external_url", "رابط خارجي"),
                            ("document", "مستند"),
                        ],
                        default="image",
                        max_length=20,
                        verbose_name="نوع الوسيط",
                    ),
                ),
                (
                    "alt_text_ar",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="النص البديل"
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        verbose_name="النص البديل بالإنجليزية",
                    ),
                ),
                (
                    "caption_ar",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="التسمية"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="التسمية بالإنجليزية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكتبة الوسائط",
                "verbose_name_plural": "مكتبة الوسائط",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="productmedia",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_media",
                to="catalog.mediaasset",
                verbose_name="مكتبة الوسائط",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["media_type", "is_active", "created_at"],
                name="catalog_med_media_t_cb9e59_idx",
            ),
        ),
    ]
