# Generated by Django 5.2.17 on 2026-08-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_internetbandwidthprofile_internetpartner_and_more"),
        ("internet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wifinetwork",
            name="bandwidth_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.internetbandwidthprofile",
            ),
        ),
        migrations.AddField(
            model_name="wifinetwork",
            name="network_backend",
            field=models.CharField(
                choices=[("manual", "يدوي"), ("mikrotik", "MikroTik")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wifinetwork",
            name="network_type",
            field=models.CharField(
                choices=[("free", "مجانية"), ("paid", "مدفوعة"), ("staff", "موظفون")],
                default="paid",
                max_length=12,
            ),
        ),
    ]
