# Generated by Django 5.2.17 on 2026-08-11 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def generalize_existing_memberships(apps, schema_editor):
    MembershipPlan = apps.get_model('members', 'MembershipPlan')
    MembershipSubscription = apps.get_model('members', 'MembershipSubscription')

    period_mapping = {
        'one_time': 'none',
        'daily': 'fixed_term',
        'weekly': 'fixed_term',
        'yearly': 'annual',
        'custom': 'fixed_term',
    }
    for old_value, new_value in period_mapping.items():
        MembershipPlan.objects.filter(billing_period=old_value).update(billing_period=new_value)

    MembershipSubscription.objects.filter(status='paused').update(status='frozen')
    for subscription in MembershipSubscription.objects.select_related('plan').iterator():
        subscription.gross_amount_syp = subscription.plan.price_syp
        if subscription.status == 'active':
            subscription.activated_at = subscription.starts_at
        elif subscription.status == 'frozen':
            subscription.activated_at = subscription.starts_at
            subscription.frozen_at = subscription.updated_at
        elif subscription.status == 'cancelled':
            subscription.cancelled_at = subscription.updated_at
        subscription.save(update_fields=['gross_amount_syp', 'activated_at', 'frozen_at', 'cancelled_at'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_internetpartner_is_default_and_more"),
        ("members", "0002_memberactivationtoken_memberdevicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplan",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="term_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day(s)"),
                    ("week", "Week(s)"),
                    ("month", "Month(s)"),
                    ("year", "Year(s)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="term_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="visible_to_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="visible_to_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_membership_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="freeze_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="gross_amount_syp",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_subscriptions",
                to="core.order",
            ),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_subscriptions",
                to="core.payment",
            ),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="billing_period",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("annual", "Annual"),
                    ("fixed_term", "Fixed term"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="price_syp",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="membershipsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("frozen", "Frozen"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(generalize_existing_memberships, migrations.RunPython.noop),
        migrations.CreateModel(
            name="MemberAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("label_ar", models.CharField(blank=True, max_length=120)),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_member_attributes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "ordering": ("member_id", "code", "-granted_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("expires_at__isnull", True)),
                        fields=("member", "code"),
                        name="unique_permanent_member_attribute",
                    )
                ],
            },
        ),
    ]
