# Generated by Django 5.2.17 on 2026-08-11 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def generalize_and_snapshot_benefits(apps, schema_editor):
    Rule = apps.get_model('members', 'MembershipBenefitRule')
    Subscription = apps.get_model('members', 'MembershipSubscription')
    for rule in Rule.objects.all().iterator():
        if rule.discount_percent is not None:
            rule.benefit_type = 'product_discount_percent'
            rule.value_decimal = rule.discount_percent
        elif rule.discount_amount_syp is not None:
            rule.benefit_type = 'product_discount_fixed'
            rule.value_decimal = rule.discount_amount_syp
        elif rule.included_quantity is not None:
            rule.benefit_type = 'free_product_quantity'
            rule.value_integer = rule.included_quantity
        elif rule.included_minutes is not None:
            rule.benefit_type = 'internet_minutes' if rule.service_type == 'internet' else 'workspace_minutes'
            rule.value_integer = rule.included_minutes
        rule.metadata = dict(rule.metadata or {}, legacy_monthly_credit_syp=rule.monthly_credit_syp)
        rule.save(update_fields=['benefit_type', 'value_decimal', 'value_integer', 'metadata'])

    for subscription in Subscription.objects.select_related('plan').iterator():
        snapshot = []
        for rule in Rule.objects.filter(plan_id=subscription.plan_id, is_active=True):
            snapshot.append({
                'rule_id': rule.pk, 'benefit_type': rule.benefit_type,
                'value_decimal': str(rule.value_decimal) if rule.value_decimal is not None else None,
                'value_integer': rule.value_integer, 'value_text': rule.value_text,
                'scope_type': rule.scope_type, 'scope_code': rule.scope_code,
                'usage_limit': rule.usage_limit, 'usage_period': rule.usage_period,
                'priority': rule.priority, 'metadata': rule.metadata,
                'product_id': rule.product_id, 'category_id': rule.category_id,
                'menu_section_id': rule.menu_section_id, 'tag_id': rule.tag_id,
                'item_type': rule.item_type, 'beverage_type': rule.beverage_type,
                'food_type': rule.food_type, 'service_type': rule.service_type,
                'applies_to_alcohol': rule.applies_to_alcohol,
            })
        subscription.benefit_snapshot = snapshot
        subscription.save(update_fields=['benefit_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_internetpartner_is_default_and_more"),
        ("members", "0003_membershipplan_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name_ar", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("open", "مفتوح"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغى"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="benefit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_discount_fixed", "خصم ثابت على منتج"),
                    ("product_discount_percent", "نسبة خصم على منتج"),
                    ("event_discount_percent", "نسبة خصم على فعالية"),
                    ("booking_priority", "أولوية الحجز"),
                    ("workspace_minutes", "دقائق مساحة العمل"),
                    ("internet_minutes", "دقائق الإنترنت"),
                    ("internet_member_price", "سعر إنترنت للأعضاء"),
                    ("free_product_quantity", "كمية منتج مجانية"),
                    ("early_access", "وصول مبكر"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="scope_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="scope_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="usage_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="usage_period",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="value_decimal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="value_integer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="value_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="benefit_snapshot",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.RunPython(generalize_and_snapshot_benefits, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ProgramEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_name", models.CharField(blank=True, max_length=160)),
                ("participant_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("active", "نشط"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغى"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_enrollments",
                        to="core.member",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_enrollments",
                        to="core.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_enrollments",
                        to="core.payment",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="members.program",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_enrollments",
                        to="members.membershipsubscription",
                    ),
                ),
            ],
        ),
    ]
