# Generated by Django 5.2.17 on 2026-08-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_internetentitlement_origin_type_and_more"),
        ("members", "0004_add_membership_benefits_and_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="commercial_allocation_syp",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="internet_bandwidth_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership_benefit_rules",
                to="core.internetbandwidthprofile",
            ),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="max_concurrent_devices",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="max_registered_devices",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CommercialAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("membership", "Membership"),
                            ("internet", "Internet"),
                            ("workspace", "Workspace"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_benefit_rule_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("allocated_amount_syp", models.PositiveBigIntegerField()),
                ("partner_name_snapshot", models.CharField(blank=True, max_length=120)),
                (
                    "partner_share_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "partner_share_amount_syp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internet_entitlement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_allocation",
                        to="core.internetentitlement",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_allocations",
                        to="core.internetpartner",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_allocations",
                        to="members.membershipsubscription",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "subscription",
                            "component_type",
                            "source_benefit_rule_id",
                        ),
                        name="unique_subscription_commercial_component",
                    )
                ],
            },
        ),
    ]
