# Generated by Django 5.2.17 on 2026-08-12 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_internetentitlement_origin_type_and_more"),
        ("members", "0005_membershipbenefitrule_commercial_allocation_syp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplan",
            name="catalog_product",
            field=models.OneToOneField(
                blank=True,
                help_text="Stable hidden catalog identity used for commercial membership sales.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership_plan",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="activation_error",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="is_complimentary",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="sale_idempotency_key",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="membershipsubscription",
            name="sale_request_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="membershipsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gross_amount_syp__isnull", True),
                    ("gross_amount_syp__gte", 0),
                    _connector="OR",
                ),
                name="membership_subscription_gross_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="membership_subscription_dates_valid",
            ),
        ),
    ]
