# Generated by Django 5.2.17 on 2026-08-12 22:24

from django.db import migrations, models


def reject_duplicate_residuals(apps, schema_editor):
    Allocation = apps.get_model('members', 'CommercialAllocation')
    duplicates = (Allocation.objects.filter(component_type='membership', source_benefit_rule_id__isnull=True)
                  .values('subscription_id').annotate(count=models.Count('id')).filter(count__gt=1))
    ids = list(duplicates.values_list('subscription_id', flat=True)[:20])
    if ids:
        raise RuntimeError(
            'Cannot add residual allocation uniqueness: duplicate membership residual rows '
            f'exist for subscription IDs {ids}. Financial history was not modified.')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_internetnetworkoperation"),
        ("members", "0006_membershipplan_catalog_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipbenefitrule",
            name="complimentary_partner_service",
            field=models.BooleanField(
                default=False,
                help_text="Explicitly exempts a complimentary Internet benefit from partner revenue share.",
            ),
        ),
        migrations.RunPython(reject_duplicate_residuals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="commercialallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("component_type", "membership"),
                    ("source_benefit_rule_id__isnull", True),
                ),
                fields=("subscription",),
                name="unique_subscription_residual_membership",
            ),
        ),
    ]
