# Generated by Django 5.2.17 on 2026-08-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0007_membershipbenefitrule_complimentary_partner_service_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipsubscription",
            name="total_frozen_duration_seconds",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
