# Generated by Django 5.2.17 on 2026-08-13 00:08

from django.db import migrations, models


def preflight(apps, schema_editor):
    Allocation = apps.get_model('members', 'CommercialAllocation')
    invalid = list(Allocation.objects.exclude(allocated_amount_syp__gte=0).values_list('pk', flat=True)[:20])
    invalid_percent = list(Allocation.objects.exclude(partner_share_percent__isnull=True)
                           .exclude(partner_share_percent__range=(0, 100)).values_list('pk', flat=True)[:20])
    if invalid or invalid_percent:
        raise RuntimeError('Commercial allocation constraint preflight failed; no history was changed: '
                           f'negative rows={invalid}, invalid percentages={invalid_percent}')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_internetentitlement_sale_request_fingerprint_and_more"),
        ("members", "0008_membershipsubscription_total_frozen_duration_seconds"),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="commercialallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_amount_syp__gte", 0)),
                name="commercial_allocation_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("partner_share_percent__isnull", True),
                    models.Q(
                        ("partner_share_percent__gte", 0),
                        ("partner_share_percent__lte", 100),
                    ),
                    _connector="OR",
                ),
                name="commercial_allocation_share_percent_range",
            ),
        ),
    ]
